### ISSUE TITLE
Suggested Site

### ISSUE THREAD

**Issue by techteacher47** [Xonshiz/comic-dl#10]
Could you please add http://www.omgbeaupeep.com to your list of supported sites? Thank you!

**Comment by Xonshiz** [comment]
Could you please provide me with example links?

1.) Link 1 : Link to a chapter of a comic

2.) Link 2 : Link to the series. Place which holds all the links to a particular comic.

**Comment by Xonshiz** [comment]
Support added!

**Comment by techteacher47** [comment]
Thank you!
