### ISSUE TITLE
[ Question ] If I put the binary in the %PATH%?

### ISSUE THREAD

**Issue by DyeffersonAz** [Xonshiz/comic-dl#100]
It will download the comic into the folder that the CMD are or in the location of the binary itself?

**Comment by Xonshiz** [comment]
It should download it in the location of the binary. Wherever it is executed from. If you want to give a specific folder and put comic_dl in PATH, I'd recommend you check #99 . It'll give you more insight on this thing. You could use the config. At this point, you're gonna have to make it manually. But, if you wait for a few days, @dsanchezseco is working on it and might release it in a few days.

I hope that answers your question. I'm closing this issue. But, if there's something more about this, please continue.

**Comment by DyeffersonAz** [comment]
In your opinion, is this advantageous to put the binary in the %PATH%?

**Comment by Xonshiz** [comment]
You won't have to go to the directory of the binary over and over again for downloading. Put it there once, make the config and call the binary from anywhere.
