### ISSUE TITLE
Python3 AttributeError: 'str' object has no attribute 'decode'

### ISSUE THREAD

**Issue by dsanchezseco** [Xonshiz/comic-dl#102]
Seems that the decode function is deprecated on python3, so the version should be check or something to avoid problems(see https://github.com/opendatakosovo/cyrillic-transliteration/issues/8 for example)

```
  File "comic-dl/comic_dl/sites/readComicBooksOnline.py", line 94, in full_series
    if (str(chapter_range).split("-")[1]).decode().isdecimal():
AttributeError: 'str' object has no attribute 'decode'
```

**Comment by Xonshiz** [comment]
I'll look into it later today/tomorrow and fix a few things :)

**Comment by dsanchezseco** [comment]
Thanks!
