### ISSUE TITLE
Update config file when finished downloading

### ISSUE THREAD

**Issue by dsanchezseco** [Xonshiz/comic-dl#103]
Now the file its updated at start, so if the download its cancelled the next execution won't download anything.
If the config it's updated at the end the download can be restarted from where it ended(skipping already downloaded files)

**Comment by Xonshiz** [comment]
I'll be closing this, since you  fixed it yourself haha.

**Comment by dsanchezseco** [comment]
I thought it was going to take me longer to do it hahahaha

**Comment by StrangeDOS** [comment]
when will this change get rolled up into the Windows binary?

**Comment by Xonshiz** [comment]
In a few hours. I'm not around my system right now. Update should be up in
next 10 hours or so.

**Comment by Xonshiz** [comment]
Released the binary, check on your ends please.
