### ISSUE TITLE
Directory deleted, even if --keep is used

### ISSUE THREAD

**Issue by StrangeDOS** [Xonshiz/comic-dl#105]
This isn't something new.  I've seen this since I started testing the Windows binary.  I just keep forgetting to submit a bug.

Here are the steps to reproduce....

1. Use comic_dl to download a comic (does matter which one or from what site), and use the --keep switch so the .jpg files are all saved.  Also, use the --convert switch to create .cbz files.

2. Download the same comic a second time, using the same --convert and --keep switches.

Expected:
1. A .cbz file and a folder is created for each comic book.  This was done on the first run.
2. A .zip file is created on the second run (because the .cbz file already exists).

What really happens:
1. A .cbz file and a folder is created for each comic book.  This was done on the first run.
2. A .zip file is created on the second run (because the .cbz file already exists). AND...the directory holding the .jpg files is deleted.

**Comment by Xonshiz** [comment]
Yeah, the reason why I included this was because the particular chapter/issue already exists and there's no need to create a new one. So, delete the files.

**Comment by StrangeDOS** [comment]
That would make sense for default behavior but I'm explicitly trying to keep the .jpgs when I use the --keep switch.

**Comment by dsanchezseco** [comment]
@StrangeDOS are you using `--keep` or `--keep yes/True`? I made that mistake at first. Maybe the --keep flag doesn't have to take parameters. 

Also, if no --conversion is provided --keep should be enforced to true, otherwise the files are deleted immediately after downloading.

**Comment by StrangeDOS** [comment]
--keep yes

**Comment by Xonshiz** [comment]
Keep takes an argument. I have some other project I'm working on currently. I'll get back to this is a few days.

**Comment by StrangeDOS** [comment]
Works great now.
