### ISSUE TITLE
Make HQBR supported

### ISSUE THREAD

**Issue by DyeffersonAz** [Xonshiz/comic-dl#108]
Hello, I'd like that this site: https://www.hqbr.com.br

be supported on comic-dl, what do you think?

This is a website that collects portuguese versions of comic books, it is the largest site of Brazil!

**Comment by DyeffersonAz** [comment]
Example links:

Comic series: https://hqbr.com.br/hq/Aves%20de%20Rapina%20(1999)?rndad=3134943408-1518549728
Issue: https://hqbr.com.br/hqs/Aves%20de%20Rapina%20(1999)/capitulo/49/

**Comment by DyeffersonAz** [comment]
@Xonshiz , what do you think about it?

**Comment by Xonshiz** [comment]
Oh crap I totally forgot to reply. Yes, I'll look into it sure :)

**Comment by DyeffersonAz** [comment]
Why did you close?

**Comment by Xonshiz** [comment]
Because I've added the support for this website. Check the latest release.

>
