### ISSUE TITLE
Add Hoopla support

### ISSUE THREAD

**Issue by 3mru** [Xonshiz/comic-dl#110]
Add support to this website
https://www.hoopladigital.com/my/hoopla
They have a great collection of comics and I'm ready to provide an account if needed.

Thanks in advance

**Comment by Xonshiz** [comment]
I'll need an account to inspect this website. I cannot give an estimation when I'll get back to this. I have few other requests to complete first. I'll let you know when I can look into this, then you can provide me the login details.

**Comment by Xonshiz** [comment]
I'm closing this, as you haven't replied and I have no account on that website.
