### ISSUE TITLE
Payment Method

### ISSUE THREAD

**Issue by GhantaBhai** [Xonshiz/comic-dl#113]
Please add # **Debit Card** Payment Method also for private repositories...
Because i don't have any Credit Card and not using Paypal Account....

**Comment by Xonshiz** [comment]
Hey,
Sorry I don't understand this part bout "Private Repositories".

**Comment by jaxxa** [comment]
Private Repositories are one of the things that you get with a GitHub subscription. https://github.com/pricing

I looks to me like he does not understand that these are Issues for your GitHub repository and not general GitHub support.

**Comment by Xonshiz** [comment]
Yeah, about private repo I know. I was confused about why @GhantaBhai mentioned it here lol.

@GhantaBhai : Mate, I believe you are confused. If you want to get in touch with the Github team, please contact them via [THIS LINK](https://enterprise.github.com/support). This place is not for that. Sorry, can't help you with this.
