### ISSUE TITLE
Access denied

### ISSUE THREAD

**Issue by DyeffersonAz** [Xonshiz/comic-dl#114]
I can't send a print because my windows is in Portuguese.
Using: Binary
I coudn't put the log because the exe even executes!

It was working perfectly and suddenly this error came.

**Comment by Xonshiz** [comment]
Please explain properly, what did you do? What actually happened? You can still generate logs even if the application works. Please provide proper information so I can look into it.

**Comment by DyeffersonAz** [comment]
![image](https://user-images.githubusercontent.com/16638560/36941394-074feda6-1f39-11e8-9d02-935fea7aca3e.png)

In the security tab:
![image](https://user-images.githubusercontent.com/16638560/36941407-5efaa64a-1f39-11e8-975f-26c91621055e.png)

Tip: translate with google translator

**Comment by Xonshiz** [comment]
Hey, please include the command your gave as well.I really do not want to type it out. Also, run the program with `--verbose` option. To me it seems like there is not write permission to the script in that folder. Try moving it somewhere else.

**Comment by DyeffersonAz** [comment]
comic_dl.exe -i http://readcomiconline.to/Comic/Thor-Son-of-Asgard -rn 2-12 --convert cbz --verbose

Using the verbose mode, there is no log. 

Note: I tried to move it to another folder, but the same happen. Even when I download again the binary from this repository!

**Comment by Xonshiz** [comment]
Okay, I'll look into this. Thanks for all the information :)

**Comment by DyeffersonAz** [comment]
Take away this label!

**Comment by DyeffersonAz** [comment]
Is this only happening with me?

:(

**Comment by DyeffersonAz** [comment]
Is it difficult?

**Comment by Xonshiz** [comment]
Could you try downloading the new binary and use it? And don't keep it in the same directory as of this one.

**Comment by Xonshiz** [comment]
That's a valid point. But, I'm confused which file is he talking about. The
binary itself or the actual downloaded files.

If it is the binary itself, then yes, the exception will be the workaround.
Otherwise, it's just some permission problem.

I hope it's just the anti-virus exception problem.

**Comment by DyeffersonAz** [comment]
@Xonshiz So, it is with the binary, and the antivirus do not popped up anything. And like I said, the CMD said "Access denied" like if the permission was denied. But when I check on the properties of my file (binary), it says that I have already gave the permission to it.

**Comment by DyeffersonAz** [comment]
And I tried to move the file. It doesn't work too.

**Comment by Xonshiz** [comment]
Okay try this. Download the latest version of comic-dl and then open your antivirus, go to its  "Exception" area and add the newly downloaded comic-dl.exe to that exception list and then try to run the binary.

**Comment by DyeffersonAz** [comment]
So, I deactivated my antivirus (PandaFREE) and then it worked!
