### ISSUE TITLE
Support for comicextra.com

### ISSUE THREAD

**Issue by pnupy** [Xonshiz/comic-dl#116]
Could support be added for www.comicextra.com? They each have some comics that I haven't been able to find elsewhere.

Thanks!

**Comment by Xonshiz** [comment]
Please open separate issues for different website requests...

**Comment by pnupy** [comment]
I have moved the request for readcomics.io to #117

**Comment by FxStryker** [comment]
The windows binary .exe is stating comicextra.net is not supported at the moment despite being on the list.

**Comment by DarklySatanic** [comment]
> The windows binary .exe is stating comicextra.net is not supported at the moment despite being on the list.

I highly doubt the list is current.
