### ISSUE TITLE
[3200] Failed to execute script __main__

### ISSUE THREAD

**Issue by MrSolution98** [Xonshiz/comic-dl#120]
![screenshot_1](https://user-images.githubusercontent.com/38131024/38418159-8fe58b36-399b-11e8-9ecf-188616ac7efb.png)

**I have done the pip update but I still get the same results. For a couple of days now, I cannot download anything from readcomiconline.to**

**Comment by DeadmanGER** [comment]
Same problem here. Updated pip and cloudflare. Hope for update in next weeks.

**Comment by StrangeDOS** [comment]
I was gone for a couple months but I see you have other testers.  Just tried the new version and this issue seems to be fixed. 

Love the text output "Fooling CloudFlare...Please wait".   Awesome.
