### ISSUE TITLE
No pages found downloading from readcomiconline.to

### ISSUE THREAD

**Issue by tenorxander95** [Xonshiz/comic-dl#121]
![image](https://user-images.githubusercontent.com/34009303/38546971-9fde2662-3c73-11e8-82f7-895c633d46b8.png)

https://gist.github.com/tenorxander95/84e161c039a0db651f16a16159954e37

Earlier today the program was working correctly on the site, then it stopped in the middle of a series and wouldn't download anymore.  I've been using the Windows binary and just tried the python version and it does the same thing.  The screenshot is what comes up when it's used.  A folder is created for the comic but nothing gets added to it since it says that there are no pages found to download

**Comment by Xonshiz** [comment]
I'll have to check this, because CloudFlare changed something and the cfscrape library has been acting weird since then. I need to update things.
