### ISSUE TITLE
comicextra.com supported but not? [Broken Support]

### ISSUE THREAD

**Issue by ModuRaziel** [Xonshiz/comic-dl#124]
When I try to run a query against comicextra.com i get the following;

![image](https://user-images.githubusercontent.com/26442932/39315916-d4425e4e-4945-11e8-86b6-515e8c45c6d5.png)

**Comment by Girbons** [comment]
Did you have an older version of comic-dl?

**Comment by ModuRaziel** [comment]
I do not. Only started using this tool earlier this week

**Comment by Girbons** [comment]
Did you already try to download the latest version?

**Comment by Xonshiz** [comment]
You seem to have an older version.The latest version supports comicextra. I just checked. But, I think they changed something and it's broken. So, I'll have to fix it.
