### ISSUE TITLE
Empty comics with readcomiconline.to

### ISSUE THREAD

**Issue by BarbetM** [Xonshiz/comic-dl#132]
When I try to download a comics on readcomiconline.to, I get Total Pages 0.
My Logs are available [HERE](https://gist.github.com/BarbetM/92c2167fb025d432449502cb1efb7bcf)

I downloaded a few Comics on this website (4-5 in a  hour) and can still access the site on chrome or firefox without any captcha needed.

Thanks for your help.

**Comment by Xonshiz** [comment]
Replicated the issue on my end. Seems like there's an issue with just this url : "http://readcomiconline.to/Comic/Fantastic-Four-1961/Issue-5". I'll look into this later tonight and upload a fix.
