### ISSUE TITLE
Settings in config.json not being used

### ISSUE THREAD

**Issue by StrangeDOS** [Xonshiz/comic-dl#133]
In the first entry of the file....

    "download_directory": "F:\\DownloadComicOngoing", 
    "comics": {
        "http://readcomiconline.to/Comic/1001-Nights": {
            "url": "http://readcomiconline.to/Comic/1001-Nights", 
            "username": "None", 
            "comic_language": "0", 
            "password": "None", 
            "next": 21
        }

...the "next" setting isn't being used correctly.  First, somehow it is getting set to higher than the number of issues that are available (in this case there are only 10 issues).  

Second, even if I manually change the "next" setting to "11", or even if I just leave it as it is, the Windows binary will still attempt to download the entire series again.

Attaching the config.json and screenshot of the directory.
Current Version : 2018.04.29

[config.json.txt](https://github.com/Xonshiz/comic-dl/files/1998765/config.json.txt)
![2018-05-13_13-55-41](https://user-images.githubusercontent.com/20542548/39970283-b8d2fd70-56b6-11e8-996e-6f96558f0128.jpg)

**Comment by Xonshiz** [comment]
@dsanchezseco could you please look into this when you get time?

**Comment by Xonshiz** [comment]
Also, after checking the  `config.json`, I see that in the `http://readcomiconline.to/Comic/4001-A-D-X-O-Manowar`, there is one chapter, so the next shouldn't be `0`, as written in the `config.json`.

**Comment by dsanchezseco** [comment]
Ummm that 21 is odd, i'll check it this afternoon(hopefully, kinda busy with work). in that case it should be 10(arrays start at 0 you know...) Same for the manowar one, the zero is the first issue so that one it's Okey.

I'll try to test it but i'm on mac.

I was thinking to improved it and update the next issue in real time for if the download its halted continue from there.

ps: actually @StrangeDOS can you confirm there's no config-lock.json next to the config.json? it's the temp file to know what to download. it should be removed when the auto finishes, but if it's halted it remains in the system, so the system continues with the previous execution.

i'll try my best to have it this afternoon (CST).

**Comment by Xonshiz** [comment]
Ah that explains the 0 count. But, I'm kind of torn between keeping it from
the perspective of ARRAY or keeping it from the perspective of the user,
i.e.,the count Starting from 1. The latter one will make things clearer for
the user. Or, we should note this down somewhere in the documentation, so
that we don't forget this later on.

No issues, take your time. I've been busy with my college as well. Need
them grades lol. I should be able to get some time in mid June, after my
semester. Need to develop a GUI for this as well.

**Comment by dsanchezseco** [comment]
@Xonshiz hahahaha i'll add the +1 then. it was straight forward from the return of the scrapper so i did it that way.

The GUI sounds awesome! Additionally...

**Comment by StrangeDOS** [comment]
Just checked my directory.  Yes, the config.json.lock got left behind.  So it didn't clean up.

**Comment by dsanchezseco** [comment]
So that's why it's starting from zero always, because the execution didn't end and the file wasn't removed. It'll try to directly update the config.json instead of using a tmp to prevent this

**Comment by dsanchezseco** [comment]
The initial zero has being changed. Nothing else was needed to make the next chapter match the one to download in the config. I'll proceed with the online update of the config instead of using the tmp
