### ISSUE TITLE
Improve auto downloader when too many series produces CF DoS protection

### ISSUE THREAD

**Issue by dsanchezseco** [Xonshiz/comic-dl#134]
When downloading heavily Cloudfare prevents the script to continue working w/o entering manually in the web. So if you are using the auto downloader this made a totally mess: empty issues & downloader thinks everything is correct and marked issues as downloaded...

Should implement a way to recognice this state and stop execution of autodownloader to continue when user intereaction is made

**Comment by dsanchezseco** [comment]
i've identified this the past week and had to do all the redownload manually after validating the catpcha

**Comment by Xonshiz** [comment]
This is a good find. Some of the issues downloading from such sites return the same. I'll try to look into this within this month, before 23rd, or at least I'll try to :P

**Comment by Xonshiz** [comment]
Added in #190
