### ISSUE TITLE
fix prepend_zeroes

### ISSUE THREAD

**Issue by darodi** [Xonshiz/comic-dl#136]
There is a problem with the current implementation.

for example:

result = globalFunctions.GlobalFunctions().prepend_zeroes(20, 200)
print(result)

returns 20 instead of 020

check the definition of 

```
   def zfill(self, width): 
        """
        S.zfill(width) -> string
        
        Pad a numeric string S with zeros on the left, to fill a field
        of the specified width.  The string S is never truncated.
        """
```

width is the desired final width, not the width of the prefix to add.

In this example, chapter 1.11 has 239 images.

`       __main__.py -cid 4e70e97cc092255ef70029dd -r 1-2`

**Comment by Xonshiz** [comment]
Since you've fixed this issue and the PR has been merged, I'm closing this issue :)
