### ISSUE TITLE
Cannot find comic_dl.exe

### ISSUE THREAD

**Issue by whitewolves** [Xonshiz/comic-dl#138]
Hi, I cannot find the comic_dl.EXE file on your site, as I have in the past.  I see exeMake.bat, but I don't know how to use it. Do I need to install Python? Thanks.
Best regards,

**Comment by Xonshiz** [comment]
Please read the description thoroughly. It clearly mentions where you can find the [Windows Binary](https://github.com/Xonshiz/comic-dl#windows-binary). If you're new to Github, I'd recommend that you go through the documentation before opening an issue, as most (if not all) the information is mentioned in it. :)

**Comment by Xonshiz** [comment]
And no, you do not need that `exeMake.bat` or Python installed. But, you do need NodeJS on your system's path. Please go through the documentation for detailed information.
