### ISSUE TITLE
Not working on readcomiconline

### ISSUE THREAD

**Issue by Joshuawaaw** [Xonshiz/comic-dl#145]
![screenshot 23](https://user-images.githubusercontent.com/40256870/41476433-1e9185d0-70f4-11e8-9355-3e96922d49d4.png)
is this a bug or is it just me?

**Comment by Xonshiz** [comment]
Check the Readme and include the verbose log file.

**Comment by PolarLuna** [comment]
![Comic-dl Screenshot](https://user-images.githubusercontent.com/56490466/66707862-4de29a00-ed7a-11e9-952b-be0310ced20c.jpg)
Am I doing it incorrectly, because it is not pulling up the images. Thank you!
