### ISSUE TITLE
Downloading Series from Manga sites doesn't work

### ISSUE THREAD

**Issue by satoshi656** [Xonshiz/comic-dl#147]
Command invoked in Windows Binary: comic_dl -c and then comic_dl -a
I expected to be able to add the link to mangarock to my .json and then download it with the auto command. I have experienced this issue from several supported manga websites.

https://gist.github.com/satoshi656/9027a41deb361a416ee74c10857e06fa

**Comment by darodi** [comment]
might work with solution for #148

**Comment by Xonshiz** [comment]
I'm closing this one, as the websites have been added in auto download feature.
