### ISSUE TITLE
Compacter and easy to use progress bar: tqdm

### ISSUE THREAD

**Issue by kidpixo** [Xonshiz/comic-dl#153]
(This is copied from #123)

I was thinking about tinkering witht the download bar, instead a progress for single page a progress for each chater could be easyier.

Diving in the code I understood each single manga has its parser and then uses common functions from `globalFunctions.py` ,  in particular `downloader` is also spitting out the progress bar.

There a lot of places where information are printed to the screen anyway, this could almost entirally removed and use a more informative progress indicator, I think.

I use a lot [tqdm/tqdm: A fast, extensible progress bar for Python and CLI](https://github.com/tqdm/tqdm) a lot lately, is really great and you can manipulate the progress bar and nest really easily.

In our case you can simply do 

```python
# code on the manga, i.e. generate the chapter list
for i in tqdm.tqdm.(manga_chapters_list):
    # code on each chapter, i.e. extract each single page link
    for i in tqdm.tqdm.(chapter_pages_list):
        # code on each page, i.e. download them
        globalFunctions.GlobalFunctions().downloader
```

**Comment by kidpixo** [comment]
@dsanchezseco thanks, seems to work. I don't have much time either, this is a side hobby for something I find useful.

Just a question you all know better : do I need to change each single scraper or I can work only on the `globalFunctions.py` ? 

in the first case I would not try at all, to much work!

![screen shot 2018-07-09 at 09 16 22](https://user-images.githubusercontent.com/2255209/42436007-d423dea4-8358-11e8-8b17-b74406b52c59.jpg)

Developing in Docker :-D

**Comment by dsanchezseco** [comment]
follow up from previous thread ```@kidpixo from my part feel free to mod the code. I'm kind on busy nowadays and I have little time to spare on this, so thanks! Any improvement is welcome.



Well i suppose that it depends on how you made it. I think that maybe, as it happen in my case with the auto donwloader you'll have to code the function once in the globalFuntions.py for example and then just add it to the different scrappers in a copy/paste fashion(with little mods as some var names change).
```

**Comment by kidpixo** [comment]
Ok, 
here an example : 

![screen shot 2018-07-09 at 09 53 56](https://user-images.githubusercontent.com/2255209/42437738-47ed65ee-835e-11e8-8ffd-bca2df2c7430.jpg)

The lines are:

1.  a progress bar for the whole manga, that advances each time the second level is done.
2. (below) progress for the chapter,  advances for each single page loaded
3. (below)  progress for the single image, advances for each single chunk downloaded.

I had to mock `globalFunctions.GlobalFunctions().info_printer()` to just pass, it s called in each single scraper, but seems to work and now it uses a lot less screen space!

**Comment by kidpixo** [comment]
It was easier than I thought  :-D

Stupid as I am I did the changes in master... 

I'll open a separate issue to discuss this and try to put everything in a new branch.

Last questions : 
- is my impression or all this is still heavilly python 2?
- do you use [Gitter](https://gitter.im/)? you can open a channel for stupid questions (like a couple I have). It is a chat linked to github repos.

Right, sorry!

@Xonshiz I created a [develop](https://github.com/kidpixo/comic-dl/tree/develop) in my fork , if you create one here too I can PR a merge.

You can find all the mods there.

Better not start to mess with master with experiments...

**Comment by kidpixo** [comment]
@Xonshiz could you please create a develop branch here, so I can PR my code ?

**Comment by Xonshiz** [comment]
Haven't been able to follow up on these conversations. Going through the last reply, I'll make a dev branch. @dsanchezseco

**Comment by Xonshiz** [comment]
Okay, it's done.

**Comment by kidpixo** [comment]
Open PR https://github.com/Xonshiz/comic-dl/pull/159 for first draft of this functionality.

**Comment by dsanchezseco** [comment]
@kidpixo have you tried on a linux machine? the output looks like [this](https://asciinema.org/a/8zb2RN7eEqhTI43NbB9qHUnRN). Is missing the chapter info, it kinda overwrites the lines...

**Comment by kidpixo** [comment]
I'm running it only in Docker, so yes, it is a linux distro, in
particular  python:3.6.5-stretch
(Debian 9) from https://hub.docker.com/_/python/ .

This seems really strange, normally it is caused from other commands other
tqdm spitting output to stdout or calls to several tqdm progress bars not
properly nested.

I can look into it next week.

**Comment by dsanchezseco** [comment]
@Xonshiz same as the referenced PR
