### ISSUE TITLE
Blanks between pulled issues on command prompt

### ISSUE THREAD

**Issue by Istovi** [Xonshiz/comic-dl#16]
At first, readcomiconline.to worked then eventually got to the point where they just state "issue 1" then blank then "issue 2" and so on in their headers. The folder doesn't show up. I tested both entire series and individual issue links, same thing.

**Comment by Xonshiz** [comment]
Please check the readme and see how to post the issues. Edit your query accordingly.

**Comment by Xonshiz** [comment]
This "Human Snag" should be fixed now.
