### ISSUE TITLE
Can't download

### ISSUE THREAD

**Issue by DyeffersonAz** [Xonshiz/comic-dl#163]
Verbose mode script: 
[Error_Log.log](https://github.com/Xonshiz/comic-dl/files/2320790/Error_Log.log)

I was trying to download, but after the first issue downloaded, it stopped.
![image](https://user-images.githubusercontent.com/16638560/44619454-fa06b000-a85c-11e8-9b43-768a58bc4f77.png)

Note: using `-rn` instead, it works fine.

**Comment by darodi** [comment]
I suppose you are using the last binary for windows.

You could use that binary here instead
https://github.com/darodi/comic-dl/releases/download/2018.07.20-fix/comic_dl.exe


@Xonshiz 
Could you build a windows binary release with the last fixes in master?

**Comment by Xonshiz** [comment]
Hey, sorry for not following for past few updates. Office keeps me busy. I'll check things again and post updated binary in 2 days from now.

**Comment by Xonshiz** [comment]
Checked on my end and latest binaries don't have this issue.
Same Issues : #163 , #165 , #169
