### ISSUE TITLE
Windows Binary crashes dowloading from readcomiconline.to

### ISSUE THREAD

**Issue by andrelopesmrx** [Xonshiz/comic-dl#165]
Windows Binary barfs trying to download a complete Volume (All issues), from readcomiconline.to:

E:\TEMP>comic_dl.exe --verbose --convert cbz --quality High --input https://readcomiconline.to/Comic/Strangers-in-Paradise

***Starting the script in Verbose Mode***

Fooling CloudFlare...Please Wait...
Fooling CloudFlare...Please Wait...

     =====================================================================
                       Manga Name : Strangers In Paradise
                          Chapter Number - Issue - 90
                                Total Pages - 30
     =====================================================================

[Comic-dl] Downloading : 01.jpg
[################################] 397/397 - 00:00:00
[Comic-dl] Downloading : 02.jpg
[################################] 395/395 - 00:00:00
[Comic-dl] Downloading : 03.jpg
[################################] 404/404 - 00:00:00
[Comic-dl] Downloading : 04.jpg
[################################] 52/52 - 00:00:00
[Comic-dl] Downloading : 05.jpg
[################################] 425/425 - 00:00:00
[Comic-dl] Downloading : 06.jpg
[################################] 484/484 - 00:00:00
[Comic-dl] Downloading : 07.jpg
[################################] 497/497 - 00:00:00
[Comic-dl] Downloading : 08.jpg
[################################] 476/476 - 00:00:00
[Comic-dl] Downloading : 09.jpg
[################################] 431/431 - 00:00:00
[Comic-dl] Downloading : 10.jpg
[################################] 479/479 - 00:00:00
[Comic-dl] Downloading : 11.jpg
[################################] 817/817 - 00:00:00
[Comic-dl] Downloading : 12.jpg
[################################] 491/491 - 00:00:00
[Comic-dl] Downloading : 13.jpg
[################################] 501/501 - 00:00:00
[Comic-dl] Downloading : 14.jpg
[################################] 543/543 - 00:00:00
[Comic-dl] Downloading : 15.jpg
[################################] 484/484 - 00:00:00
[Comic-dl] Downloading : 16.jpg
[################################] 467/467 - 00:00:00
[Comic-dl] Downloading : 17.jpg
[################################] 424/424 - 00:00:00
[Comic-dl] Downloading : 18.jpg
[################################] 483/483 - 00:00:00
[Comic-dl] Downloading : 19.jpg
[################################] 460/460 - 00:00:00
[Comic-dl] Downloading : 20.jpg
[################################] 435/435 - 00:00:00
[Comic-dl] Downloading : 21.jpg
[################################] 546/546 - 00:00:00
[Comic-dl] Downloading : 22.jpg
[################################] 515/515 - 00:00:00
[Comic-dl] Downloading : 23.jpg
[################################] 397/397 - 00:00:00
[Comic-dl] Downloading : 24.jpg
[################################] 670/670 - 00:00:00
[Comic-dl] Downloading : 25.jpg
[################################] 369/369 - 00:00:00
[Comic-dl] Downloading : 26.jpg
[################################] 225/225 - 00:00:00
[Comic-dl] Downloading : 27.jpg
[################################] 225/225 - 00:00:00
[Comic-dl] Downloading : 28.jpg
[################################] 291/291 - 00:00:00
[Comic-dl] Downloading : 29.jpg
[################################] 50/50 - 00:00:00
[Comic-dl] Downloading : 30.jpg
[################################] 104/104 - 00:00:00
CBZ File : E:\TEMP\Strangers In Paradise\Strangers In Paradise - Ch Issue - 90
Traceback (most recent call last):
  File "comic_dl\__main__.py", line 10, in <module>
  File "comic_dl\comic_dl.py", line 226, in __init__
  File "comic_dl\honcho.py", line 100, in checker
  File "comic_dl\sites\readcomicOnlineto.py", line 28, in __init__
  File "comic_dl\sites\readcomicOnlineto.py", line 141, in full_series
IndexError: list index out of range
[3852] Failed to execute script __main__

[Error_Log.log](https://github.com/Xonshiz/comic-dl/files/2330092/Error_Log.log)

**Comment by darodi** [comment]
duplicate of #163 , #155, #158, #145, #132

fixed in #149

**Comment by andrelopesmrx** [comment]
Does it mean the new binaries are supposed to work?

**Comment by darodi** [comment]
when the new binaries will be made available, yes.
In the meantime, you could get the pre-release given in #163

**Comment by Xonshiz** [comment]
Checked on my end and latest binaries don't have this issue.
Same Issues : #163 , #165 , #169
