### ISSUE TITLE
[Feature-Request] Genration of the PDF file from the images

### ISSUE THREAD

**Issue by RamolaWeb** [Xonshiz/comic-dl#17]
Comic-dl download the different images of the comic from the respective supported site and store in the respective location in the user 's computer. It will great to make a PDF of the images downloaded as it will be more easier and more convenient to read the comic by this ways.

**Comment by RamolaWeb** [comment]
We can use the Python Library called **Report Lab** to create the PDF from the respective images downloaded. It is very easy to use and support all the format of the file.

**Comment by Xonshiz** [comment]
It's a nice idea. I will surely get it done. Currently, I'm re-writing this whole script for improved performance and better workflow. I will surely add this feature when I push the new version :)

**Comment by RamolaWeb** [comment]
@Xonshiz  I would like to contribute for the above Feature Requested.

**Comment by Xonshiz** [comment]
Oh, that'll be great. I'll push the new version of Comic-dl by the end of this week. So, you can integrate it then.

**Comment by RamolaWeb** [comment]
@Xonshiz  Should I send A pull request for the Above Feature

**Comment by Xonshiz** [comment]
Yep, please do :)

**Comment by Xonshiz** [comment]
While you do this, make it so that it only activates and makes pdf when an argument is passed for it. We don't want it to make PDF by default.

**Comment by Xonshiz** [comment]
Should be Supported now!
