### ISSUE TITLE
Downloaded files are owned by root when using the docker image

### ISSUE THREAD

**Issue by johnchristopher** [Xonshiz/comic-dl#175]
Currently using `docker run -it --rm -v /home/user:/directory -w /directory comic-dl:py3.6.5-stretch comic_dl -dd /directory' results in downloaded files being owned by root.

Is is possible to give ownership to the current user when invoking the script through docker ?

**Comment by darodi** [comment]
are you running docker as root?

`sudo usermod -aG docker $USER`

would add your user to the docker group to be able to run docker as your user.

**Comment by johnchristopher** [comment]
> are you running docker as root?

No.

```bash
$ groups
johnchristopher adm cdrom sudo dip plugdev netdev lpadmin sambashare docker music
```

I am running a standard ubuntu 18.04.

**Comment by Xonshiz** [comment]
Will look into this.
