### ISSUE TITLE
Autodownloader downloads again latest issue when annual is included on readcomiconline.to

### ISSUE THREAD

**Issue by dsanchezseco** [Xonshiz/comic-dl#178]
Using the autodownloader on a **ongoing** series downloads an already read issue when an annual is included. 

The issue counter is increased and matches the next_issue var, but as in readcomiconline the annuals are at **the bottom of the list** the latest regular issue is downloaded instead of the annual.

No sure if it happens on other websites.
Any ideas on how to best solve it? I thought of storing the name of the latest issue downloaded and check if it matches the one the be downloaded, in case it matches look for the annuals and get the highest number one as is the most recent. Although it can lead to problems later.

Maybe a better approach is to order the list based on the publication date, but right now i don't know if that info is available on the scrapper.

Any thoughts?

**Comment by darodi** [comment]
As you say, you can keep the last index and the last file name downloaded.
If the last index + 1 matches the previous file name, just increase the index one more time.

If one annual issue was added, it will work.
If more annual issues were added it won't, but that won't happen often, annual is every year :P
and autodownloader is meant to be run regularly.

**Comment by dsanchezseco** [comment]
Sure, it's meant to happen once a year, but it means to "manually" download the annual.
The index is not a big problem as it's uipdated anyway but the lastest regular issue is downloaded twice(in the previous run and in the current).

I'll fiddle with the publication field that is on the page when i had some time and see if something can be done.

Pd: also thinking if we do the last_downloaded_name check and more then one issue has been added since the previous run we can have more troubles than we are solving.
