### ISSUE TITLE
To download it in the correct order.

### ISSUE THREAD

**Issue by DyeffersonAz** [Xonshiz/comic-dl#184]
When we put an entire comic series to download, the software starts from the last one. It could be an argument or just the default that it starts from the first issue/annual depending on the website.

**Comment by dsanchezseco** [comment]
@DyeffersonAz  are you looking for this?

```  -s SORTING, --sorting SORTING
                        Decides downloading order of chapters.
```

**Comment by DyeffersonAz** [comment]
Oh, yes!
