### ISSUE TITLE
How do I use auto-download?

### ISSUE THREAD

**Issue by DyeffersonAz** [Xonshiz/comic-dl#188]
What is wrong here?
```
{
    "download_directory": "<here>", 
    "comics": {"https://readcomiconline.to/Comic/Superman-1939/Issue-30?id=16133", "https://readcomiconline.to/Comic/All-American-Comics-1939/Issue-61?id=45782"}, 
    "conversion": "cbz", 
    "keep": "True", 
    "sorting_order": "ascending", 
    "image_quality": "Best"
}
```

**Comment by dsanchezseco** [comment]
@DyeffersonAz do not manually create the archive, use the -c option to use the "wizard" and after that use the -a to download all. Way easier.

When using the -c the only required field is the url so you can leave the default values for the rest of fields just by tapping <enter>

TL;DR: the problem there is the comics attribute the array contains objects that have the comic url, next chapter to download, language, ....

**Comment by Xonshiz** [comment]
I'll be closing this, as it seems that @dsanchezseco has replied accordingly. Please feel free to re-open.
