### ISSUE TITLE
comic site

### ISSUE THREAD

**Issue by mijaconc** [Xonshiz/comic-dl#19]
Dear Xonshiz,

Thank you very much for your script. Is there any possibility to add this site to your script for download comics: http://striputopija.blogspot.si/. It's very nice site with comics from ex-Yugoslavija in which 
I was raised in. 

Keep up the good work.

Best regards,

**Comment by Xonshiz** [comment]
Will look into it.

**Comment by mijaconc** [comment]
Thank you very much.

**Comment by mijaconc** [comment]
Dear Xonshiz,

I am sorry for being annoying, but did you manage to find time to look into site  http://striputopija.blogspot.si? 

 I am looking forward to hearing from you soon. 

Thank you for time and excellent script. 

Best regards,

**Comment by Xonshiz** [comment]
Yes, I looked into the website. It's easy to scrap. But, I haven't been getting time to look and fix things, unfortunately. I'll see what I can do. I do this in my free time.

**Comment by mijaconc** [comment]
Ok, thank you very much.

**Comment by Xonshiz** [comment]
Support added! (FINALLY)!

**Comment by Xonshiz** [comment]
Oh yes, please do check on your end and let me know if there's any problem.
Example URLs : 

    Single : http://striputopija.blogspot.in/2016/05/001_54.html
    Full : http://striputopija.blogspot.in/p/biser-strip.html


I've check it on these, check on others. Windows build should follow within a few minutes.

**Comment by mijaconc** [comment]
Dear Xonshiz,

your script works like a charm, altough sometimes it confuses with the issues in one collection and download issues from other collections. It works if you download issue by issue, but if you download full collection, then sometimes this problem occurs. No harm done, if problem occurs, then I will download issue by issue in those cases. Will test it some more. Thank you very much again, you make my life and lifes of my children more beautiful.  

Best regards,

**Comment by Xonshiz** [comment]
Thank you for such praise. The issue you're facing is weird. It would be great if you could share those links here with me so that I can double check and debug on my end.

This shouldn't happen. However, if it continues, please open a new Issue for it and report it over there so I can look into it when I get time.

**Comment by mijaconc** [comment]
Dear Xonshiz,

thank you for your kindness, will try with other collections, will report what is happening and share those links and reports. Thanks again. 

Best regards,
