### ISSUE TITLE
site request: mangadex.org

### ISSUE THREAD

**Issue by tidux** [Xonshiz/comic-dl#195]
Example series URL: https://mangadex.org/title/19104/murenase-shiiton-gakuen

Example chapter URL: https://mangadex.org/chapter/89143

**Comment by EarthBoundX5** [comment]
I'd like to request this as well!

**Comment by Xonshiz** [comment]
Done, but they've changed their URL scheme since that time you requested this. New schemes:

Whole Series URL:  https://mangadex.org/title/19465f6a-1c11-4179-891e-68293402b883
Specific Chapter URL: https://mangadex.org/chapter/17fd3a89-605d-4f6a-93be-71e559e0889c/1
