### ISSUE TITLE
mangafox broken

### ISSUE THREAD

**Issue by darodi** [Xonshiz/comic-dl#196]
Mangafox is broken.

They changed the way the web reader displays images:
For example:

http://fanfox.net/manga/shokugeki_no_soma/v01/c002/1.html

The page contains 

```
 var comicid = 11529;        var chapterid =190399;   
```

and this script

```
eval(function(p,a,c,k,e,d){e=function(c){return(c<a?"":e(parseInt(c/a)))+((c=c%a)>35?String.fromCharCode(c+29):c.toString(36))};if(!''.replace(/^/,String)){while(c--)d[e(c)]=k[c]||e(c);k=[function(e){return d[e]}];e=function(){return'\\w+'};c=1;};while(c--)if(k[c])p=p.replace(new RegExp('\\b'+e(c)+'\\b','g'),k[c]);return p;}('5 4=\'\'+\'7\'+\'c\'+\'6\'+\'1\'+\'3\'+\'8\'+\'2\'+\'0\'+\'7\'+\'2\'+\'6\'+\'2\'+\'9\'+\'6\'+\'c\'+\'7\';$("#a").b(4);',13,13,'||f||guidkey|var|||||dm5_key|val|'.split('|'),0,{}))
```

decoded using http://jsnice.org/
we get:

```
'use strict';
/** @type {string} */
var guidkey = "" + "7" + "c" + "6" + "1" + "3" + "8" + "f" + "0" + "7" + "f" + "6" + "f" + "9" + "6" + "c" + "7";
$("#dm5_key").val(guidkey);
```
the var guidkey  or the element with id dm5_key contains the key.

Then an ajax call is done with the chapterid and the key above:
http://fanfox.net/manga/shokugeki_no_soma/v01/c002/chapterfun.ashx?cid=190399&page=1&key=7c6138f07f6f96c7

that calls returns:

```
eval(function(p,a,c,k,e,d){e=function(c){return(c<a?"":e(parseInt(c/a)))+((c=c%a)>35?String.fromCharCode(c+29):c.toString(36))};if(!''.replace(/^/,String)){while(c--)d[e(c)]=k[c]||e(c);k=[function(e){return d[e]}];e=function(){return'\\w+'};c=1;};while(c--)if(k[c])p=p.replace(new RegExp('\\b'+e(c)+'\\b','g'),k[c]);return p;}('t f(){2 e="n://s.7.3/4/5/6/c-h.0/g";2 1=["/m.9?8=o&b=a","/l.9?8=k&b=a"];u(2 i=0;i<1.p;i++){q(i==0){1[i]="//s.7.3/4/5/6/c-h.0/g"+1[i];r}1[i]=e+1[i]}j 1}2 d;d=f();',31,31,'|pvalue|var|net|store|manga|11529|fanfox|token|jpg|1542816000|ttl|01||pix|dm5imagefun|compressed|002||return|24813edc41414532360fd23ecc4ea75ab2411ae7|c0002|c000|http|e9ff6f53c5af047b5f2b57ea01774b93ae8e5249|length|if|continue||function|for'.split('|'),0,{}))
```

once decoded using http://jsnice.org/
we get:

```
'use strict';
/**
 * @return {?}
 */
function dm5imagefun() {
  /** @type {string} */
  var inWorkTree = "http://s.fanfox.net/store/manga/11529/01-002.0/compressed";
  /** @type {!Array} */
  var arrLines = ["/c000.jpg?token=e9ff6f53c5af047b5f2b57ea01774b93ae8e5249&ttl=1542816000", "/c0002.jpg?token=24813edc41414532360fd23ecc4ea75ab2411ae7&ttl=1542816000"];
  /** @type {number} */
  var i = 0;
  for (; i < arrLines.length; i++) {
    if (i == 0) {
      /** @type {string} */
      arrLines[i] = "//s.fanfox.net/store/manga/11529/01-002.0/compressed" + arrLines[i];
      continue;
    }
    /** @type {string} */
    arrLines[i] = inWorkTree + arrLines[i];
  }
  return arrLines;
}
var d;
d = dm5imagefun();

```

the displayed image is :
http://s.fanfox.net/store/manga/11529/01-002.0/compressed/c000.jpg?token=e9ff6f53c5af047b5f2b57ea01774b93ae8e5249&ttl=1542816000

### **TODO**

- parsing the page to get the scripts dans the values is quite easy.
- what is less easy is a way to evaluate the scrambled javascript in python.
   - I've found this:
      - https://stackoverflow.com/questions/10136319/executing-javascript-from-python/30537286#30537286

**Comment by Xonshiz** [comment]
Thank you so much for all this great research. It'll save a lot of time.
I'll look at this in a few days and will try to fix it.

**Comment by Xonshiz** [comment]
I'll try to look into this by the end of this week probably.

**Comment by UMLAUTaxl** [comment]
Is it fixed?
(This app was a big download and a big hassle to install. Don't tell me this whole thing is broken ...)

**Comment by Xonshiz** [comment]
Yes this was fixed in today's commit and @UMLAUTaxl this is not an "app", rather a "command line script". It wouldn't work by "double clicking" it. Please check the readme for instructions if you're stuck anywhere.
