### ISSUE TITLE
How to change download location?

### ISSUE THREAD

**Issue by TheEscPilot** [Xonshiz/comic-dl#20]
Hi! (Love the app and the Readme, very easy to follow!) 
I've got about 4 HDD's on my PC and a Raided NAS that I'm using for storage. 
Currently, the script is stored and running on my G:/ (full path "G:\Downloads\Comic_dl\comic-dl.exe") 

When it completes successfully it initially downloads the .jpg files to C:/, then organizes them into C:\%Comic name%\%Comic number%\

Anyway that I can change both the initial download location AND the final storage location? 
I'd love to be able to point this at my NAS (or mounted folder location), and have this script skip my SSD (C:\) entirely.

**Comment by Xonshiz** [comment]
Unfortunately, currently you can't do this. However, I'll try to include this feature in the future version.

**Comment by TheEscPilot** [comment]
<3 <3 <3 
Many appreciations!

**Comment by Xonshiz** [comment]
Option added. Check the readme for more information.
