### ISSUE TITLE
Can't download manga from "http://fanfox.net/"

### ISSUE THREAD

**Issue by remmington457555** [Xonshiz/comic-dl#201]
I can't download manga from "http://fanfox.net/"

could you add more sites to the script such as:-
https://kissmanga.com/
https://mangakakalot.com/manga/online_the_comic
https://ww1.manga-fox.com/

**Comment by Xonshiz** [comment]
This website seems to be broken, as mentioned in #196. Will be closing this one, because these are same.

And for the website addition request, please make a separate issue and mention these,.
