### ISSUE TITLE
Issue: Total pages 0 

### ISSUE THREAD

**Issue by andres8h** [Xonshiz/comic-dl#204]
![issue](https://user-images.githubusercontent.com/4030967/50326967-9874ec00-04b2-11e9-9bf8-08fc2d82f136.JPG)
Hi! 
I was downloading normally but then this issue happened and i cant download anymore... :(
its from https://readcomiconline.to/

**Comment by Xonshiz** [comment]
Just tried downloading with the latest binary. It's working just fine. Please download the latest release and then try again.

![image](https://user-images.githubusercontent.com/13240567/51781226-dc0ae780-213b-11e9-85cf-fff605b6381b.png)
