### ISSUE TITLE
Problems with fooling Cloudflare

### ISSUE THREAD

**Issue by Lofter1** [Xonshiz/comic-dl#209]
When i try to download from readcomiconline, comic-dl gets stuck at the "fooling cloudflare"-phase.

**Comment by thehyperborean** [comment]
Same here:

comic_dl.exe -dd Y:\Comics\Downloaded --convert cbz -i https://readcomiconline.to/Comic/American-Vampire
Fooling CloudFlare...Please Wait...
Fooling CloudFlare...Please Wait...
ERROR:root:Error downloading : http://readcomiconline.to/Comic/American-Vampire/Issue-34?id=63502
Total Time Taken To Complete : 23.9639999866

**Comment by Lofter1** [comment]
> Same here:
> 
> comic_dl.exe -dd Y:\Comics\Downloaded --convert cbz -i https://readcomiconline.to/Comic/American-Vampire
> Fooling CloudFlare...Please Wait...
> Fooling CloudFlare...Please Wait...
> ERROR:root:Error downloading : http://readcomiconline.to/Comic/American-Vampire/Issue-34?id=63502
> Total Time Taken To Complete : 23.9639999866

seems like yours doesn't have to do with fooling cloudflare. you at least come to the point where he tries to download the comic. i think it would be better to try to trouble-shoot it and if nothing works, open your own issue with describing what's wrong

**Comment by Xonshiz** [comment]
Please run the application with "--verbose" flag and share the log file that gets created.

**Comment by whitewolves** [comment]
"Error_Log.log" file content: 

DEBUG: Arguments Provided : Namespace(auto=False, chapter_id=None, config=False, convert=None, download_directory=['C:\\BIG_G\\COMIC-DL\\WORKING'], force_download=False, input=['https://readcomiconline.to/Comic/Thor-For-Asgard/Issue-1?id=61813'], keep=['True'], manga_language='0', page_id=None, password=['None'], print_index=False, quality='True', range='All', search=None, skip_cache='0', sorting=None, username=['None'], verbose=True, version=False)
DEBUG: Operating System : Windows - 10 - 10.0.17763
DEBUG: Python Version : 2.7.14 (32bit)
DEBUG: Script Version : 2019.01.26
DEBUG: Comic Url : https://readcomiconline.to/Comic/Thor-For-Asgard/Issue-1?id=61813
DEBUG: Selected Domain : readcomiconline.to
DEBUG: Starting new HTTPS connection (1): readcomiconline.to:443
DEBUG: https://readcomiconline.to:443 "GET /Comic/Thor-For-Asgard/Issue-1?id=61813 HTTP/1.1" 503 None

============================
Also, this information appears on the CMD screen after running comic_dl.exe:

***Starting the script in Verbose Mode***

Fooling CloudFlare...Please Wait...
Traceback (most recent call last):
  File "comic_dl\__main__.py", line 10, in <module>
  File "comic_dl\comic_dl.py", line 237, in __init__
  File "comic_dl\honcho.py", line 101, in checker
  File "comic_dl\sites\readcomicOnlineto.py", line 36, in __init__
  File "comic_dl\sites\readcomicOnlineto.py", line 43, in single_chapter
  File "comic_dl\globalFunctions.py", line 38, in page_downloader
  File "site-packages\requests\sessions.py", line 525, in get
  File "site-packages\cfscrape\__init__.py", line 68, in request
  File "site-packages\cfscrape\__init__.py", line 97, in solve_cf_challenge
  File "site-packages\cfscrape\__init__.py", line 127, in solve_challenge
ValueError: Error parsing Cloudflare IUAM Javascript challenge. Cloudflare may h
ave changed their technique, or there may be a bug in the script.

Please read https://github.com/Anorov/cloudflare-scrape#updates, then file a bug
 report at https://github.com/Anorov/cloudflare-scrape/issues."
[6972] Failed to execute script __main__

**Comment by Oooli62** [comment]
Hello there.
Did you happen to see this? https://github.com/Anorov/cloudflare-scrape/issues/193
Couldn't this be perhaps included in a new release?

**Comment by johnchristopher** [comment]
The fix was applied to 1.9.7 version of cfscrape (10 minutes ago). Once pypi has it `pip install -U cfscrape` should fix the problem. Or rebuild the docker image.

**Comment by abuhamsa** [comment]
@johnchristopher I think @Oooli62  is talking about the windows binary which @Xonshiz builds and releases.

**Comment by johnchristopher** [comment]
@abuhamsa: My bad.

**Comment by dsanchezseco** [comment]
Solved updating cfscrape library
