### ISSUE TITLE
New site addition.

### ISSUE THREAD

**Issue by Young-Angelo** [Xonshiz/comic-dl#213]
Could you please add http://freecomiclibrary.com/. It's a great site with tons of comics.
BTW .. the linux tutorial/how-to is a little outdated. In order to install comic-dl on linux ,you have to manually install soupsieve and install beautifulsoup4 system-wide using apt package manager.

**Comment by Xonshiz** [comment]
Thought of working on this, looks like the website no longer exists. Closing this one. If the URL has changed, please re-open and share the latest URL for this website.
Thanks
