### ISSUE TITLE
Unable to download Series that have annuals and TPBs while single issues download without any problems

### ISSUE THREAD

**Issue by AlecHex** [Xonshiz/comic-dl#217]
I have recently found out about this and even though there is an error while downloading from readcomiconline.to the other sites are working perfectly. I used the website comicextra.com

**Command You Gave** : I tried three different URLs in the basic script comic_dl.exe -i  "(URL)" 

**Expected Behaviour** : The three URLs were different, one being of a comic included Annuals in the beginning, the other with a TPB and the last with only single issue comics. I expected them to download the former two commands to download them without any problems.

**Actual Behaviour** : The command for the former two just ended. Ii have included the three logs respectively below. 

**Link To Gist**: https://gist.github.com/AlecHex/60cd27448b24885b25ee20ae8adb466e

Is there anything wrong or am I to change or add something in the command itself to make this work.

**Comment by Danieltrue** [comment]
Use this command and it will work (comic_dl -i  URL -dd  to any folder) it will download everything

**Comment by AlecHex** [comment]
> 
> 
> Use this command and it will work (comic_dl -i URL -dd to any folder) it will download everything

This command still doesn't work

**Comment by Xonshiz** [comment]
I'll check this on my end and try to reproduce this issue.

**Comment by Aemilian666** [comment]
No updates, I see.

**Comment by Xonshiz** [comment]
I've pushed an update for readcomiconline.li. Could you please follow #299  and verify whether this issue has been fixed or not. I'm closing this for now, but if the issue persists, please re-open.
