### ISSUE TITLE
No longer works with readcomiconline.to

### ISSUE THREAD

**Issue by edimusxero** [Xonshiz/comic-dl#219]
They changed something on readcomiconline.to and comic-dl no longer works.  There is an open ticket for cfscrape as well as it may be related to that.

**Comment by DaRockJaeger** [comment]
Yes, fixing readcomicsonline.to would be great.
They changed their CloudFlare algorithms.

You can read more on
https://github.com/Anorov/cloudflare-scrape#updates,

**Comment by dsanchezseco** [comment]
Is already working since a week or so ago, the problem is on the lib so doing a 

> pip(3) install -r requirements.txt

 should fixed it (if you are using the source code)

**Comment by dsanchezseco** [comment]
See #209
