### ISSUE TITLE
Broken Install?

### ISSUE THREAD

**Issue by sethcohn** [Xonshiz/comic-dl#22]
Tried installing on both Debian and Mac, without success. (and with python 2.7. and 3.6, using pyenv)
Setup seems broken, could never get things to work, ie CLI wasn't ever responsive...

**Comment by Xonshiz** [comment]
don't use the setup.py file. Just follow the instructions mentioned in the ReadMe and it should work.

**Comment by sethcohn** [comment]
No, I tried the exact instructions (even the phantomjs stuff which isn't needed anymore, is it?), and no go.  I run the command ./comic_dl.py and CLI returns without an error.  Same for -h, --version,  etc

[minor edit to remove personal info below]
$ pip install -r requirements.txt
Requirement already satisfied: bs4 in .pyenv/versions/2.7.12/lib/python2.7/site-packages (from -r requirements.txt (line 1))
Requirement already satisfied: requests in /usr/local/lib/python2.7/site-packages (from -r requirements.txt (line 2))
Requirement already satisfied: cfscrape in .pyenv/versions/2.7.12/lib/python2.7/site-packages (from -r requirements.txt (line 3))
Requirement already satisfied: clint in .pyenv/versions/2.7.12/lib/python2.7/site-packages (from -r requirements.txt (line 4))
Requirement already satisfied: beautifulsoup4 in .pyenv/versions/2.7.12/lib/python2.7/site-packages (from bs4->-r requirements.txt (line 1))
Requirement already satisfied: PyExecJS>=1.4.0 in .pyenv/versions/2.7.12/lib/python2.7/site-packages (from cfscrape->-r requirements.txt (line 3))
Requirement already satisfied: args in .pyenv/versions/2.7.12/lib/python2.7/site-packages (from clint->-r requirements.txt (line 4))
Requirement already satisfied: six==1.10.0 in /usr/local/lib/python2.7/site-packages (from PyExecJS>=1.4.0->cfscrape->-r requirements.txt (line 3))

I know enough Python to know something's not right with the code... I git cloned, and I tried downloading your master zip.  Neither works correctly (and as I said, on multiple different systems, OSX and Debian/Ubuntu).  Something's afoot... Please review the instructions.  And fix the setup for those of us who want to do an install and use the CLI correctly.

**Comment by Xonshiz** [comment]
Try running `__main__.py --version`

**Comment by sethcohn** [comment]
Yes, that works correctly.  As does giving it a -i url
so comic-dl.py isn't working but __main__.py is working for me.

**Comment by Xonshiz** [comment]
That is how to use this script. When I wrote the older script, it had no classes and the over all code sucked and was slow in over all performance. Now, I forgot to update the read me. Thanks for bringing this up. :)

**Comment by Xonshiz** [comment]
`__main__.py` passes the command line arguments to `comic_dl.py`. Read [this SO answer](https://stackoverflow.com/a/4043007) if you want to know a little bit more about `__main__.py` files.
