### ISSUE TITLE
Official cfscrape not updated

### ISSUE THREAD

**Issue by Lofter1** [Xonshiz/comic-dl#225]
Seems like the official cfscrape is not getting an update for the new cloudflare check any time soon, might consider (temporarily) using a working fork of it?

**Comment by hallwayorchard** [comment]
Where does this leave us?

**Comment by Lofter1** [comment]
While it is a workaround, I wouldn't like this approach as a user because of reasons users have stated in that Issue

**Comment by uaarrgghh** [comment]
I've changed it to cloudscraper, now it's working again.
here is my pull-request https://github.com/Xonshiz/comic-dl/pull/229

**Comment by Lofter1** [comment]
Lets hope Xonshiz didn't decide to let comic-dl die, too, in favour of his newer project.

**Comment by Dissentrix** [comment]
I'm not sure how to use the workaround for cfscrape, talked about above - it seems that project is dead in the water, and the comic-dl binary doesn't seem to work right now. I hope new instructions/a new way of bypassing cloudflare are going to be posted at some point.

Also, shouldn't comic-dl's error log redirect you to this tool's issues page? As you can see [here](https://github.com/Anorov/cloudflare-scrape/issues/240) I opened an issue on the cfscrape page, which is obviously not the correct place, as I'm very new to this whole thing.

**Comment by Lofter1** [comment]
> Also, shouldn't comic-dl's error log redirect you to this tool's issues page? As you can see [here](https://github.com/Anorov/cloudflare-scrape/issues/240) I opened an issue on the cfscrape page, which is obviously not the correct place, as I'm very new to this whole thing.

No, the error is coming from cfscrape, not comic-dl, so cfscrape is directing you to it's own repository. 

Let's hope xonshiz is updating the repository with uaarrgghh's pull-request soon, cause the workaround isn't the best way to solve the issue either. The new pull-request is the best way to fix the problem for now.

**Comment by Lofter1** [comment]
Ah never mind, i just saw Anorov updated cf-scrape now. We just need to update it, too. I think the issue is closed with this.
