### ISSUE TITLE
Very short timeouts?

### ISSUE THREAD

**Issue by vomov** [Xonshiz/comic-dl#23]
Downloading seems to break after a while, which can happen due to captcha's or whatever. Usually, I just resume, but this gives an error within the first few images: can't connect to server (503). It does detect that the images are already downloaded, and after running it again on a different comic, I got the same error after a while. Deleting the downloaded files and restarting gave the same behavior, but at different moments. However, when running it without partially downloaded comics, it keeps downloading for a couple of minutes, while it throws the error in seconds if there are files present.

I suspect that there are some very short timeouts that set the server off, but I'm not sure. Would it be possible to look into this? Incidentally, speed is not really an issue; i accumulate several comics, and then use a batch file to make it download the whole list every once in a while.

EDIT: added log below
`DEBUG: Arguments Provided : Namespace(input=['http://mangafox.me/manga/shingeki_no_kyojin/'], sorting=None, verbose=True, version=False)
DEBUG: Operating System : Windows - 10 - 10.0.15063
DEBUG: Python Version : 2.7.13 (32bit)
DEBUG: Comic Url : http://mangafox.me/manga/shingeki_no_kyojin/
DEBUG: Selected Domain : mangafox.me
DEBUG: Starting new HTTP connection (1): mangafox.me
DEBUG: http://mangafox.me:80 "GET /manga/shingeki_no_kyojin/ HTTP/1.1" 200 None
DEBUG: All Links : ['http://mangafox.me/manga/shingeki_no_kyojin/vTBD/c091/1.html', 'http://mangafox.me/manga/shingeki_no_kyojin/v22/c090/1.html', 'http://mangafox.me/manga/shingeki_no_kyojin/v22/c089/1.html', 'http://mangafox.me/manga/shingeki_no_kyojin/v22/c088/1.html', 'http://mangafox.me/manga/shingeki_no_kyojin/v22/c087/1.html', 'http://mangafox.me/manga/shingeki_no_kyojin/v21/c086/1.html', 'http://mangafox.me/manga/shingeki_no_kyojin/v21/c085/1.html', 'http://mangafox.me/manga/shingeki_no_kyojin/v21/c084/1.html', 'http://mangafox.me/manga/shingeki_no_kyojin/v21/c083/1.html', 'http://mangafox.me/manga/shingeki_no_kyojin/v20/c082/1.html', 'http://mangafox.me/manga/shingeki_no_kyojin/v20/c081/1.html', 'http://mangafox.me/manga/shingeki_no_kyojin/v20/c080/1.html', 'http://mangafox.me/manga/shingeki_no_kyojin/v20/c079/1.html', 'http://mangafox.me/manga/shingeki_no_kyojin/v19/c078/1.html', 'http://mangafox.me/manga/shingeki_no_kyojin/v19/c077/1.html', 'http://mangafox.me/manga/shingeki_no_kyojin/v19/c076/1.html', 'http://mangafox.me/manga/shingeki_no_kyojin/v19/c075/1.html', 'http://mangafox.me/manga/shingeki_no_kyojin/v18/c074/1.html', 'http://mangafox.me/manga/shingeki_no_kyojin/v18/c073/1.html', 'http://mangafox.me/manga/shingeki_no_kyojin/v18/c072/1.html', 'http://mangafox.me/manga/shingeki_no_kyojin/v18/c071/1.html', 'http://mangafox.me/manga/shingeki_no_kyojin/v17/c070/1.html', 'http://mangafox.me/manga/shingeki_no_kyojin/v17/c069/1.html', 'http://mangafox.me/manga/shingeki_no_kyojin/v17/c068/1.html', 'http://mangafox.me/manga/shingeki_no_kyojin/v17/c067/1.html', 'http://mangafox.me/manga/shingeki_no_kyojin/v16/c066/1.html', 'http://mangafox.me/manga/shingeki_no_kyojin/v16/c065/1.html', 'http://mangafox.me/manga/shingeki_no_kyojin/v16/c064/1.html', 'http://mangafox.me/manga/shingeki_no_kyojin/v16/c063/1.html', 'http://mangafox.me/manga/shingeki_no_kyojin/v15/c062/1.html', 'http://mangafox.me/manga/shingeki_no_kyojin/v15/c061/1.html', 'http://mangafox.me/manga/shingeki_no_kyojin/v15/c060/1.html', 'http://mangafox.me/manga/shingeki_no_kyojin/v15/c059/1.html', 'http://mangafox.me/manga/shingeki_no_kyojin/v14/c058/1.html', 'http://mangafox.me/manga/shingeki_no_kyojin/v14/c057/1.html', 'http://mangafox.me/manga/shingeki_no_kyojin/v14/c056/1.html', 'http://mangafox.me/manga/shingeki_no_kyojin/v14/c055/1.html', 'http://mangafox.me/manga/shingeki_no_kyojin/v13/c054/1.html', 'http://mangafox.me/manga/shingeki_no_kyojin/v13/c053/1.html', 'http://mangafox.me/manga/shingeki_no_kyojin/v13/c052/1.html', 'http://mangafox.me/manga/shingeki_no_kyojin/v13/c051.1/1.html', 'http://mangafox.me/manga/shingeki_no_kyojin/v13/c051/1.html', 'http://mangafox.me/manga/shingeki_no_kyojin/v12/c050.1/1.html', 'http://mangafox.me/manga/shingeki_no_kyojin/v12/c050/1.html', 'http://mangafox.me/manga/shingeki_no_kyojin/v12/c049/1.html', 'http://mangafox.me/manga/shingeki_no_kyojin/v12/c048/1.html', 'http://mangafox.me/manga/shingeki_no_kyojin/v12/c047/1.html', 'http://mangafox.me/manga/shingeki_no_kyojin/v11/c046/1.html', 'http://mangafox.me/manga/shingeki_no_kyojin/v11/c045/1.html', 'http://mangafox.me/manga/shingeki_no_kyojin/v11/c044/1.html', 'http://mangafox.me/manga/shingeki_no_kyojin/v11/c043/1.html', 'http://mangafox.me/manga/shingeki_no_kyojin/v10/c042/1.html', 'http://mangafox.me/manga/shingeki_no_kyojin/v10/c041/1.html', 'http://mangafox.me/manga/shingeki_no_kyojin/v10/c040/1.html', 'http://mangafox.me/manga/shingeki_no_kyojin/v10/c039/1.html', 'http://mangafox.me/manga/shingeki_no_kyojin/v09/c038/1.html', 'http://mangafox.me/manga/shingeki_no_kyojin/v09/c037/1.html', 'http://mangafox.me/manga/shingeki_no_kyojin/v09/c036/1.html', 'http://mangafox.me/manga/shingeki_no_kyojin/v09/c035/1.html', 'http://mangafox.me/manga/shingeki_no_kyojin/v08/c034/1.html', 'http://mangafox.me/manga/shingeki_no_kyojin/v08/c033/1.html', 'http://mangafox.me/manga/shingeki_no_kyojin/v08/c032/1.html', 'http://mangafox.me/manga/shingeki_no_kyojin/v08/c031/1.html', 'http://mangafox.me/manga/shingeki_no_kyojin/v07/c030/1.html', 'http://mangafox.me/manga/shingeki_no_kyojin/v07/c029/1.html', 'http://mangafox.me/manga/shingeki_no_kyojin/v07/c028/1.html', 'http://mangafox.me/manga/shingeki_no_kyojin/v07/c027/1.html', 'http://mangafox.me/manga/shingeki_no_kyojin/v06/c026/1.html', 'http://mangafox.me/manga/shingeki_no_kyojin/v06/c025/1.html', 'http://mangafox.me/manga/shingeki_no_kyojin/v06/c024/1.html', 'http://mangafox.me/manga/shingeki_no_kyojin/v06/c023/1.html', 'http://mangafox.me/manga/shingeki_no_kyojin/v05/c022/1.html', 'http://mangafox.me/manga/shingeki_no_kyojin/v05/c021/1.html', 'http://mangafox.me/manga/shingeki_no_kyojin/v05/c020/1.html', 'http://mangafox.me/manga/shingeki_no_kyojin/v05/c019/1.html', 'http://mangafox.me/manga/shingeki_no_kyojin/v05/c018.5/1.html', 'http://mangafox.me/manga/shingeki_no_kyojin/v04/c018/1.html', 'http://mangafox.me/manga/shingeki_no_kyojin/v04/c017/1.html', 'http://mangafox.me/manga/shingeki_no_kyojin/v04/c016/1.html', 'http://mangafox.me/manga/shingeki_no_kyojin/v04/c015/1.html', 'http://mangafox.me/manga/shingeki_no_kyojin/v04/c014/1.html', 'http://mangafox.me/manga/shingeki_no_kyojin/v03/c013/1.html', 'http://mangafox.me/manga/shingeki_no_kyojin/v03/c012/1.html', 'http://mangafox.me/manga/shingeki_no_kyojin/v03/c011/1.html', 'http://mangafox.me/manga/shingeki_no_kyojin/v03/c010/1.html', 'http://mangafox.me/manga/shingeki_no_kyojin/v03/c009.5/1.html', 'http://mangafox.me/manga/shingeki_no_kyojin/v01/c001.5/1.html', 'http://mangafox.me/manga/shingeki_no_kyojin/v00/c000/1.html']
DEBUG: Starting new HTTP connection (1): mangafox.me
DEBUG: http://mangafox.me:80 "GET /manga/shingeki_no_kyojin/v00/c000/1.html HTTP/1.1" 200 None
DEBUG: Chapter Url : http://mangafox.me/manga/shingeki_no_kyojin/v00/c000/1.html
DEBUG: Starting new HTTP connection (1): mangafox.me
DEBUG: http://mangafox.me:80 "GET /manga/shingeki_no_kyojin/v00/c000/1.html HTTP/1.1" 200 None
DEBUG: Image Link : http://h.mfcdn.net/store/manga/9011/00-000.0/compressed/v001.jpg?token=c8bff0d0ab362d538db02be3ac99aeaa&ttl=1497805200
DEBUG: File Check Path : D:\com\Shingeki No Kyojin\000/01.jpg
DEBUG: Download File Name : 01.jpg
DEBUG: Chapter Url : http://mangafox.me/manga/shingeki_no_kyojin/v00/c000/2.html
DEBUG: Starting new HTTP connection (1): mangafox.me
DEBUG: http://mangafox.me:80 "GET /manga/shingeki_no_kyojin/v00/c000/2.html HTTP/1.1" 200 None
DEBUG: Image Link : http://h.mfcdn.net/store/manga/9011/00-000.0/compressed/v002.jpg?token=1c9937909c99116367e849ebd36284fd&ttl=1497798000
DEBUG: File Check Path : D:\com\Shingeki No Kyojin\000/02.jpg
DEBUG: Download File Name : 02.jpg
DEBUG: Chapter Url : http://mangafox.me/manga/shingeki_no_kyojin/v00/c000/3.html
DEBUG: Starting new HTTP connection (1): mangafox.me
DEBUG: http://mangafox.me:80 "GET /manga/shingeki_no_kyojin/v00/c000/3.html HTTP/1.1" 503 608
`

**Comment by Xonshiz** [comment]
There are no delays whatsoever. I think I should add some though. Maybe the server is shutting the connection because of so many requests in such short amount of time.

**Comment by Xonshiz** [comment]
Should be fixed...
