### ISSUE TITLE
TMO

### ISSUE THREAD

**Issue by sephiroth1993** [Xonshiz/comic-dl#231]
Can you add [TMOFans](https://tmofans.com/)? It has all of it's mangas in _**Spanish**_.
While the majority of the mangas to download with this tool are in _**English**_, i think spanish mangas will be apreciated by foreigners like me and by people who does not handle english very well.
Also, thanks for this tool, it's amazing!

**Comment by Danieltrue** [comment]
Pls sir I need your help can you give an installation process of comic-DL I am using windows  7 sir pls

**Comment by sephiroth1993** [comment]
> 
> 
> Pls sir I need your help can you give an installation process of comic-DL I am using windows 7 sir pls

https://github.com/Xonshiz/comic-dl#installation 🤔

**Comment by Xonshiz** [comment]
Added supported for TMO.
