### ISSUE TITLE
Pls create a video o. How to install the comic dl

### ISSUE THREAD

**Issue by Danieltrue** [Xonshiz/comic-dl#232]
Plz help I can't install the Comic-dl because I don't understand what you explained on the installation so pls help me out I need a video or a better explanation pls my email :danielokezie75@gmail.com to contact me thank for everything.

**Comment by Danieltrue** [comment]
I am using windows 7 os

**Comment by Xonshiz** [comment]
Hey,

The information is detailed already. I personally can't do that much.
Please look things up on YouTube.

**Comment by Chr1st-oo** [comment]
Everything you need to know about installation is documented [here](https://github.com/Xonshiz/comic-dl#windows-).

**Comment by Danieltrue** [comment]
Pls I have installed Phyton js and node.js how do I use the source code to
start downloading.

**Comment by Aemilian666** [comment]
> Everything you need to know about installation is documented [here](https://github.com/Xonshiz/comic-dl#windows-).

Not really.
