### ISSUE TITLE
Filenames need to be sanitized during conversions

### ISSUE THREAD

**Issue by GiovanH** [Xonshiz/comic-dl#234]
Comics with special characters in their names will fail with OS errors if their names contain special characters. A slug function needs to be implemented and referenced in GlobalFunctions

**Comment by GiovanH** [comment]
A very simple implementation in windows is
```Python
def easySlug(string, repl="-", directory=False):
    import re
    if directory:
        return re.sub("^\.|\.+$", "", easySlug(string, directory=False))
    else:
        return re.sub("[\\\\/:*?\"<>\|]|\ $", repl, string)
```

**Comment by Xonshiz** [comment]
Merged
