### ISSUE TITLE
Auto close 

### ISSUE THREAD

**Issue by Danieltrue** [Xonshiz/comic-dl#237]
I downloaded the Comic-dl.exe only when ever I click on it open and show nothing and after 2 sec it automatically close pls how will I go about this

**Comment by Xonshiz** [comment]
This is a CLI script. It won't run like that. Please read the documentation, everything has been mentioned in it in detail.

**Comment by Danieltrue** [comment]
Sir pls just give me a striate procedure I don't understand the documentation do I need node. Js
