### ISSUE TITLE
i cant download any comics it just downloads the folder

### ISSUE THREAD

**Issue by marlon99rocks** [Xonshiz/comic-dl#24]
DEBUG: Arguments Provided : Namespace(input=None, sorting=None, verbose=True, version=False)
DEBUG: Operating System : Windows - 10 - 10.0.15063
DEBUG: Python Version : 2.7.13 (32bit)

**Comment by Xonshiz** [comment]
In this verbose log, I can see that you're not passing any "INPUT" URL to download from.

check the readme's "Usage" section.

**Comment by marlon99rocks** [comment]
im using biney

**Comment by Xonshiz** [comment]
Doesn't matter what you're using. You're NOT giving it the "-i" argument. Refer to the video tutorial.
