### ISSUE TITLE
Readcomicbooksonline.net changed domain

### ISSUE THREAD

**Issue by SalviGG** [Xonshiz/comic-dl#242]
Hello, 
The site readcomicbookonline.net changed their domain for https://comicpunch.net
Could you please update to support this? 
Thanks in advance.

**Comment by Aemilian666** [comment]
Do you plan to answer this user's question, or not.

**Comment by Xonshiz** [comment]
Yeah that domain went down as well. I think it's something else now. Please download latest binary and see if any of the websites work for you.
