### ISSUE TITLE
Downloading from Mangarock only downloads one chapter

### ISSUE THREAD

**Issue by fuzzfactory0** [Xonshiz/comic-dl#243]
When trying to download a series from Mangarock.com, it will download a random chapter, only one and it's always the same. It doesn't convert it either, the files stay as .mri.

For example, for Catulus Syndrome, it will only download chapter 42, no matter how many times the script is executed, and regardless of if you use --range or not.

Currently using Windows binary (x86)

**Comment by Xonshiz** [comment]
Can you please post the error log?

**Comment by jaxxa** [comment]
Hi I am Encountering the same Issue, it only Downloading a single chapter and all the images being .mri files

Please Find the error log attached.

[Error_Log.log](https://github.com/Xonshiz/comic-dl/files/3638256/Error_Log.log)

**Comment by Xonshiz** [comment]
Hey, if you're interested in downloading manga and comics, for now I would
suggest to you check "CoManga". It's a GUI based utility and last time I
checked, Mangarock was working in it.



Thank You,
Dhruv Kanojia
(Github <https://github.com/Xonshiz>| Website <http://psychoticelites.com/>
| Twitter <https://twitter.com/Xonshiz> | LinkedIn
<https://in.linkedin.com/in/dhruvkanojia> | Google+
<https://plus.google.com/+DhruvKanojia>)

**Comment by jaxxa** [comment]
Thanks for the alternative.

Although I was able to get the branch by GiovanH working with Mangarock.
https://github.com/GiovanH/comic-dl
