### ISSUE TITLE
comic-dl should check for cbz before redownloading

### ISSUE THREAD

**Issue by GiovanH** [Xonshiz/comic-dl#247]
If I download a comic and convert it to a CBZ, I shouldn't need to keep the image files around. However, when updating that comic, comic-dl will redownload every image before converting to CBZ, and only when it converts does it realize that it didn't need to update that chapter at all. 

The script should simply check for the existence of the CBZ file before downloading images.

**Comment by Xonshiz** [comment]
Sure. That's a bug. Thanks for reporting. Will look into it soon!
