### ISSUE TITLE
Bug: Downloading images without "." between name and extension (01jpeg)

### ISSUE THREAD

**Issue by satishbabariya** [Xonshiz/comic-dl#249]
![Screenshot (3)](https://user-images.githubusercontent.com/16605023/64699010-8f550080-d4c1-11e9-91fe-2ddafff79f21.png)

manga source : https://www.mangaeden.com

**Comment by Xonshiz** [comment]
Hey, could you please also supply the arguments that you're using for me to reproduce this? The actual command.
