### ISSUE TITLE
i need help

### ISSUE THREAD

**Issue by marlon99rocks** [Xonshiz/comic-dl#25]
Microsoft Windows [Version 10.0.15063]
(c) 2017 Microsoft Corporation. All rights reserved.

C:\WINDOWS\system32>cd C:\Users\marlo\Desktop\stuff\comic dl\comic-dl-master\comic-dl-master

C:\Users\marlo\Desktop\stuff\comic dl\comic-dl-master\comic-dl-master>setup.py install
C:\Users\marlo\AppData\Local\Programs\Python\Python36-32\lib\distutils\dist.py:261: UserWarning: Unknown distribution option: 'install_requires'
  warnings.warn(msg)
running install
running build
running build_py
creating build
creating build\lib
creating build\lib\comic_dl
copying comic_dl\comic_dl.py -> build\lib\comic_dl
copying comic_dl\exeMaker.py -> build\lib\comic_dl
copying comic_dl\globalFunctions.py -> build\lib\comic_dl
copying comic_dl\honcho.py -> build\lib\comic_dl
copying comic_dl\__init__.py -> build\lib\comic_dl
copying comic_dl\__main__.py -> build\lib\comic_dl
copying comic_dl\__version__.py -> build\lib\comic_dl
creating build\lib\comic_dl\sites
copying comic_dl\sites\acQQ.py -> build\lib\comic_dl\sites
copying comic_dl\sites\comicNaver.py -> build\lib\comic_dl\sites
copying comic_dl\sites\foolSlide.py -> build\lib\comic_dl\sites
copying comic_dl\sites\kissmanga.py -> build\lib\comic_dl\sites
copying comic_dl\sites\mangaFox.py -> build\lib\comic_dl\sites
copying comic_dl\sites\mangaHere.py -> build\lib\comic_dl\sites
copying comic_dl\sites\omgBeauPeep.py -> build\lib\comic_dl\sites
copying comic_dl\sites\rawSenManga.py -> build\lib\comic_dl\sites
copying comic_dl\sites\readcomicOnlineto.py -> build\lib\comic_dl\sites
copying comic_dl\sites\__init__.py -> build\lib\comic_dl\sites
error: package directory 'comic_dl\downloader' does not exist

C:\Users\marlo\Desktop\stuff\comic dl\comic-dl-master\comic-dl-master>setup2.py install
Traceback (most recent call last):
  File "C:\Users\marlo\Desktop\stuff\comic dl\comic-dl-master\comic-dl-master\setup2.py", line 6, in <module>
    import comic_dl
  File "C:\Users\marlo\Desktop\stuff\comic dl\comic-dl-master\comic-dl-master\comic_dl\__init__.py", line 5, in <module>
    import comic_dl
  File "C:\Users\marlo\Desktop\stuff\comic dl\comic-dl-master\comic-dl-master\comic_dl\comic_dl.py", line 9, in <module>
    import honcho
  File "C:\Users\marlo\Desktop\stuff\comic dl\comic-dl-master\comic-dl-master\comic_dl\honcho.py", line 9, in <module>
    from sites import foolSlide
  File "C:\Users\marlo\Desktop\stuff\comic dl\comic-dl-master\comic-dl-master\comic_dl\sites\foolSlide.py", line 4, in <module>
    import globalFunctions
ImportError: No module named globalFunctions

**Comment by marlon99rocks** [comment]
how to i install globalFunctions

**Comment by Xonshiz** [comment]
If you're on windows and have no idea how python/git works, just use windows binary. Watch the video tutorial.

**Comment by Xonshiz** [comment]
Plus, refer to [this comment](https://github.com/Xonshiz/comic-dl/issues/22#issuecomment-309197706) to see more info on not using setup.py
