### ISSUE TITLE
Windows Binary not working

### ISSUE THREAD

**Issue by tauroneo** [Xonshiz/comic-dl#251]
Hello.

I tried using comic_dl after a while but I can´t get it wo work, see the the attached file for the errors. I ended it by keystroke cause the list just gets longer and longer withe the same errors just different lines
Is there a solution to it?

Greetings
![comic_dl](https://user-images.githubusercontent.com/58257503/69721279-ce840c80-1114-11ea-8980-daa49cef488e.PNG)

**Comment by Xonshiz** [comment]
Download the latest build and check now. Thanks!
