### ISSUE TITLE
mangarockhd not working

### ISSUE THREAD

**Issue by hoangvn9x** [Xonshiz/comic-dl#255]
https://api.mangarockhd.com/query/web401/pages?oid=mrs-chapter-200260585

Today, when I use the api, I get this error : "{"code":0,"data":[]}"

Do you know how to fix it?

**Comment by Pranav-Bhaskar** [comment]
Well you just cant. Mangarock is currently shutting itself down and the only way to access their manga's is to use the 'mangarock definative' mobile app which too will the closing in the monthe of march 2020. But to use the mangarock mobile api you need a qtoken too. It would be better if you leave it till the mangarock developers release their new app(which is a paid one). For more details goto [mangarock](https://mangarock.com/). It would be best for all if we close #255 issue and create a new one to remove mangarock completely from comic-dl.

**Comment by Xonshiz** [comment]
Ah, they've changed these many things? This kind of sucks. Gotta look for alternatives for this. Because Mangarock was really good and their data handling was also clean.
I'll be closing this bug for now.
