### ISSUE TITLE
python script doing nothing.

### ISSUE THREAD

**Issue by altanir84** [Xonshiz/comic-dl#260]
Hello! I'll be as brief as I can.

Windows 10 user, trying to use the python script as the binary is outdated and still unable to deal with cloudscrape. Python 3.7.7, added to PATH, added nodejs to system and user path, phantomjs-2.1.1-windows folder inside comic_dl folder.

comic_dl folder located inside python folder:
C:\Python37\comic_dl

Made a little test.py with some imports (pandas, sys and cloudscraper) and some prints to test if the python was working.

When typing __main__.py -v -i https://readcomiconline.to/Comic/Batman-2016 I just get nothing.

![image](https://user-images.githubusercontent.com/52831296/78382351-1af0c480-75ad-11ea-93ea-0da9328b0e01.png)

Please, how can I solve this?

**Comment by altanir84** [comment]
Solved by adding 

import sys
sys.path.append("C:\Python37\Lib\site-packages")

 In the beggining of every .py file.

**Comment by Xonshiz** [comment]
Your python environment isn't visible to the PATH of your system OS. Appending this line in every .py files isn't a good solution. I'd suggest that you add that directory in your $PATH variable instead. Look up "System environments" and "Path" for windows.
