### ISSUE TITLE
why is it not downloading my comics

### ISSUE THREAD

**Issue by marlon99rocks** [Xonshiz/comic-dl#27]
![image](https://user-images.githubusercontent.com/23298994/27452046-884de57a-57d4-11e7-9bf5-30789e4fabe5.png)

**Comment by Xonshiz** [comment]
Seriously, WHAT IS WRONG WITH YOU?! Which part of "[go through the Read Me](https://github.com/Xonshiz/comic-dl/issues/26#issuecomment-310283314)" do you not understand? I don't care if you're new to this, but when I've explicitly mentioned to check the read me and re-format your Issue, you HAVE to understand that.

Final warning, read this section : https://github.com/Xonshiz/comic-dl#opening-an-issuerequesting-a-site
