### ISSUE TITLE
503 from readcomiconline, regardless of ip

### ISSUE THREAD

**Issue by vengeance101** [Xonshiz/comic-dl#272]
Hi there, used this script many many times, always careful to reset VPN before 100 downloads. Recently came back to using it.

I'm getting a 503 now from readcomiconline, and it exists no matter what random IP I hop to. 

Has anyone seen this before? Wondering if the entire set of IPs from this VPN got blacklisted.

**Comment by magnuschase293** [comment]
What happens if you reach 100 downloads??? The sight recognises the ip and vanishes you???

**Comment by Xonshiz** [comment]
If you bombard any website with too many requests, this is bound to happen. Wait for a few days and try again. Also, please use the script wisely and don't try to download tons of stuff in one go. Might cause these issues and might result in a permanent ban.
