### ISSUE TITLE
[Feature-Request] Generation of the .cbz file from the images

### ISSUE THREAD

**Issue by jaxxa** [Xonshiz/comic-dl#28]
Similar to issue #17 it would be nice if we were able to produce .cbz files from directly within the program.

If you dont know these are .zip files containing jpg files. So it should be possible to zip up the images and rename the file to create these.

**Comment by Xonshiz** [comment]
Yep, I'm planning on making `.epub` as well. Since @RamolaWeb mentioned that he'd like to help in getting those PDFs, I'll be leaving that to him. I'll try to get this feature by this weekend.

**Comment by Xonshiz** [comment]
oh, thanks for the pointer. Will keep in mind (Y)

**Comment by Xonshiz** [comment]
This should work now. Check on your ends please :)

**Comment by sethcohn** [comment]
https://stackoverflow.com/questions/15750429/use-shutil-make-archive-with-zipfile-zip-stored
Using plain make archive zip means that compression is used. (which is a mistake for comic archives, and causes big delays in many readers)

https://docs.python.org/2/library/zipfile.html#zipfile-objects is the better choice, and would allow using ZIP_STORED (no compression)

**Comment by Xonshiz** [comment]
I didn't go with the `zipfile` becasue it didn't have the feature of adding multiple files at once in a compression module. `shutil` had it. I'll have to iterate over each and every image and then add it in a zip.

For now, please bear with the shutil, in near future I'll update this with the zipfile and remove the compression, as mentioned in those links. I hope that's fine. :)

**Comment by sethcohn** [comment]
Of course.  Any zip is better than no zip. :)  I just figured I'd point that out.  If someone has issues with the zip file generated, try rezipping to an uncompressed (stored) one, and compare speed/performance.

Thank you for all you do, don't mean to see ungrateful.
