### ISSUE TITLE
[linux] comic_dl.py import tqdm error

### ISSUE THREAD

**Issue by hollisticated-horse** [Xonshiz/comic-dl#280]
```
Traceback (most recent call last):
  File "./__main__.py", line 4, in <module>
    from comic_dl import ComicDL
  File "/home/user/comic-dl-master/comic_dl/comic_dl.py", line 4, in <module>
    from tqdm import tqdm
ImportError: No module named tqdm
```
ubuntu 20.10

**Comment by hollisticated-horse** [comment]
`pip3 install tqdm : 
Requirement already satisfied: tqdm in /usr/lib/python3/dist-packages (4.48.2)`

**Comment by hollisticated-horse** [comment]
never mind, i think i solved it. 

running `./__main__.py` seems to not work... 
but `python3 __main__.py [options] -i URL ` works, altough i had to `pip3 install ` two modules: `img2pdf` and `cloudscraper`

**Comment by Xonshiz** [comment]
You need to install the requirements mentioned in requirements.txt file. Closing this, as the issue was due to external libs not being installed on system.
