### ISSUE TITLE
Website request: Webtoons.com

### ISSUE THREAD

**Issue by thatrobotdev** [Xonshiz/comic-dl#284]
Hello! I'd like to request a site: https://www.webtoons.com/.

**Webtoons live under URLs like the ones below:**

https://www.webtoons.com/es/fantasy/castle-swimmer/list?title_no=1852
https://www.webtoons.com/en/fantasy/castle-swimmer/list?title_no=1499 <-- Official Spanish Translation (note the different title number)

**Each comic URL looks like this:**
https://www.webtoons.com/en/romance/super-secret/ep-10/viewer?title_no=666&episode_no=11
https://www.webtoons.com/es/fantasy/castle-swimmer/t2-ep-074/viewer?title_no=1852&episode_no=78

**Unofficial translations of Webtoons use this structure:**
https://www.webtoons.com/en/romance/super-secret/ep-10/viewer?title_no=666&episode_no=11#language_code=IND&team_version=0
https://www.webtoons.com/en/romance/super-secret/ep-10/viewer?title_no=666&episode_no=11#language_code=SPA&team_version=0

**Some webtoons have embedded audio**
https://www.webtoons.com/en/fantasy/lumine/episode-17/viewer?title_no=1022&episode_no=18

Hopefully, I covered all of the edge cases!

A similar website that is already supported is Comic Naver: https://comic.naver.com/index.nhn. I'm not sure how similar the two websites are though, since I am only a user of webtoons.

Thank you!

**Comment by Xonshiz** [comment]
added support to download comics, but not audio download yet. They've got HLS streams and there's no direct way to get those... at least I didn't have enough time to take a look into it. Maybe in future.

**Comment by thatrobotdev** [comment]
Thank you so much! I'm really excited to check the new feature out
