### ISSUE TITLE
How to open?

### ISSUE THREAD

**Issue by HalBenHB** [Xonshiz/comic-dl#285]
I'm using Windows 10 x64.

It says me "If you use the windows binary, you don't need to install anything, except Node.js."

I downloaded Node.js
I downloaded docker, docker downloaded a dozen of things I do not know.
I downloaded Phantom.js
I downloaded "THIS REPOSITORY" thing in Installation.
I downloaded comic_dl.exe

comics_dl.exe, phantom.js are inside comic-dl-master\comic_dl.

When I click comic_dl.exe, it opens a blank black program, then closes after 2 seconds.

I'm about to go crazy. How do i download and use this program? Why tutorial video is deleted?

**Comment by Xonshiz** [comment]
I would suggest that you go through the "read me/documentation" properly, as it mentions how to run this program.
Read this: [https://github.com/Xonshiz/comic-dl#windows](https://github.com/Xonshiz/comic-dl#windows)

Also, the tutorial was old, hence, made private.

**Comment by Aemilian666** [comment]
Thanks for giving zero info, since the documentation is confusing as fuck.
