### ISSUE TITLE
Cirular import error

### ISSUE THREAD

**Issue by Rebanar** [Xonshiz/comic-dl#288]
Starting with the recent builds which drop python 2 support, I get an error when trying to run. I tried on both Windows and Linux and get the error with the compiled files.

Traceback (most recent call last):
  File "__main__.py", line 4, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 540, in exec_module
  File "__init__.py", line 8, in <module>
ImportError: cannot import name 'ComicDL' from partially initialized module 'comic_dl' (most likely due to a circular import) (C:\Users\\*******\AppData\Local\Temp\_MEI2562\comic_dl\__init__.pyc)
[4104] Failed to execute script __main__

**Comment by Xonshiz** [comment]
Which python version are you on? Check your environment because these builds ran successfully on Linux, Windows and MacOS. I am not sure why you're even getting error with "Pyinstaller" in that error.
How are you trying to execute this script?

**Comment by Rebanar** [comment]
Windows:

Python is 3.9.5
Python 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] on win32
As far as executing it, I downloaded the compiled comic_dl.exe and tried to run it.

Linux:

Python is 3.8.5
Python 3.8.5 (default, May 27 2021, 13:30:53)
I'm executing it by running the comic_dl_linux compiled binary. Its error is similar to Windows, so I didn't include it, but in case it's helpful it's

./comic_dl_linux
DEPRECATION: The OpenSSL being used by this python install (OpenSSL 1.0.2g  1 Mar 2016) does not meet the minimum supported version (>= OpenSSL 1.1.1) in order to support TLS 1.3 required by Cloudflare, You may encounter an unexpected Captcha or cloudflare 1020 blocks.
Traceback (most recent call last):
  File "__main__.py", line 4, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 540, in exec_module
  File "__init__.py", line 8, in <module>
ImportError: cannot import name 'ComicDL' from partially initialized module 'comic_dl' (most likely due to a circular import) (/tmp/_MEIS4z1IK/comic_dl/__init__.pyc)
[6224] Failed to execute script __main__

**Comment by Xonshiz** [comment]
Got it.. thanks for the info. I'll take a look as soon as I get some time.

**Comment by Zaccigator** [comment]
Came here to say, I have this exact same error on windows

**Comment by scytalezero** [comment]
I'm also seeing this error on Windows with Python 3.9.5 installed using the binary release.

**Comment by Aemilian666** [comment]
This error is still relevant. 

![image](https://user-images.githubusercontent.com/66919047/129768639-ad53fdaf-29dc-400e-9ad3-c708f258aa41.png)

**Comment by Aemilian666** [comment]
![image](https://user-images.githubusercontent.com/66919047/129769165-3e67334b-0289-41d8-99ec-3bcef563b4d8.png)

**Comment by StrangeDOS** [comment]
Any traction on this?  I'm also seeing it when using the Windows binary.
![image](https://user-images.githubusercontent.com/20542548/131269474-3b5e0acc-6752-49c6-9b83-def592811bbe.png)

**Comment by Xonshiz** [comment]
Not yet.... haven't gotten time to look into this. Will try to do it this weekend...

**Comment by StrangeDOS** [comment]
Thanks Xonshiz.  Long time, no see. :)

**Comment by Xonshiz** [comment]
Hey, yep... long time no see :D hahaha good to see your name back here :D

And yes, the issue started coming when I put this on the CI pipeline to automate distributable builds. Not sure why it's causing the issue now.... but, I think I know about the fix. Just have to experiment a few things... :(

**Comment by StrangeDOS** [comment]
I can't help with the coding but as usual, I'm up for testing when you get something ready.

**Comment by Xonshiz** [comment]
Fixed this with latest merge. Tested on windows and the binary was printing the version at least. Feel free to update me if there's any such issue.
