### ISSUE TITLE
Error / no result with readcomiconline.to

### ISSUE THREAD

**Issue by JustAGit74** [Xonshiz/comic-dl#29]
I always get an error message when trying to download from above mentioned site. Attached is a gist with the error-log and the lines from the script while running.

- Browsing the site just to read works as usual
- I tried the old download script "readcomiconline downloader"  - this one does work.
- Seems it does have something to do with something "cloudflare-scrape" - I tried to look into it but usage seems to be more targeted at Linux system? (An is far above what I am capable of anyway)

[Gist](https://gist.github.com/anonymous/f7e62eb8ffde0bc4d876abcd49790f69)

Thank you for looking into this :)

Rob

**Comment by Xonshiz** [comment]
Hey, First of all, this is not the script's fault and god dammit, I need to update this read me.
Check the [Line 25](https://gist.github.com/anonymous/f7e62eb8ffde0bc4d876abcd49790f69#file-gistfile1-txt-L25) or your verbose log. You need node.js in your system's path.

So, download node.js. This is required by "Cfscrape", a python library that lets me bypass Cloudflare's anti-robot page. I'll update the documentation.

**Comment by JustAGit74** [comment]
See, this is me being an idiot who cannot even really understand the error-message.
Thank you very much for taking the time and pointing me towards the right direction!

**Comment by Xonshiz** [comment]
Sorry for the mess up. The documentation has been updated accordingly. :)

**Comment by jaxxa** [comment]
Thank you, I was also having this issue and can confirm that it is now fixed for me by following the new documentation.
