### ISSUE TITLE
readcomicsonline.ru

### ISSUE THREAD

**Issue by ysahith** [Xonshiz/comic-dl#290]
Could you add [readcomicsonline.ru](https://readcomicsonline.ru/) to the list of supported websites?

**Comment by StrangeDOS** [comment]
And readcomiconline.li

**Comment by Xonshiz** [comment]
Sure, will push an update tomorrow if I get some time and include the `.ru`, as `.li` Is already supported I guess (will check again tho).

**Comment by Xonshiz** [comment]
Closing, as added with [latest commit](https://github.com/Xonshiz/comic-dl/commit/d236e7537768310416a1663dc53163dcc386ceac).
