### ISSUE TITLE
New Windows binary isn't downloading

### ISSUE THREAD

**Issue by StrangeDOS** [Xonshiz/comic-dl#293]
Tried the new binary but it isn't downloading any images.  It does create the folder for the comic but that's it.

Used the following command...
![image](https://user-images.githubusercontent.com/20542548/132247745-40bb11c0-7b14-4230-bb56-4a25673393c6.png)

Here is my config file...
{
    "download_directory": "f:\\DownloadComic",
    "sorting_order": "descending",
    "conversion": "cbz",
    "keep": "True",
    "image_quality": "Best",
    "comics": {}
}

And here is the error file...
DEBUG: Arguments Provided : Namespace(auto=False, chapter_id=None, comic=False, comic_info=None, config=False, convert=None, download_directory=['C:\\Comic_dl'], force_download=False, input=['https://readcomiconline.li/Comic/Cyrus-Perkins-and-the-Haunted-Taxicab'], keep=['True'], manga_language='0', page_id=None, password=['None'], print_index=False, quality='True', range='All', search=None, search_comic=None, skip_cache='0', sorting=None, update=None, username=['None'], verbose=True, version=False)
DEBUG: Operating System : Windows - 10 - 10.0.19041
DEBUG: Python Version : 3.8.0 (64bit)
DEBUG: Script Version : 2021.09.04.3
DEBUG: Comic Url : https://readcomiconline.li/Comic/Cyrus-Perkins-and-the-Haunted-Taxicab
DEBUG: Selected Domain : readcomiconline.li
DEBUG: Starting new HTTPS connection (1): readcomiconline.li:443
DEBUG: https://readcomiconline.li:443 "GET /Comic/Cyrus-Perkins-and-the-Haunted-Taxicab HTTP/1.1" 200 None
DEBUG: All Links : ['/Comic/Cyrus-Perkins-and-the-Haunted-Taxicab/TPB?id=170226']
DEBUG: Starting new HTTP connection (1): readcomiconline.to:80
DEBUG: http://readcomiconline.to:80 "GET /Comic/Cyrus-Perkins-and-the-Haunted-Taxicab/TPB?id=170226 HTTP/1.1" 301 None
DEBUG: Starting new HTTPS connection (1): readcomiconline.li:443
DEBUG: https://readcomiconline.li:443 "GET /Comic/Cyrus-Perkins-and-the-Haunted-Taxicab/TPB?id=170226 HTTP/1.1" 302 None
DEBUG: https://readcomiconline.li:443 "GET /Special/AreYouHuman?reUrl=%2FComic%2FCyrus-Perkins-and-the-Haunted-Taxicab%2FTPB%3Fid%3D170226 HTTP/1.1" 200 None

**Comment by StrangeDOS** [comment]
Looking over the debug log, it looks like it is trying to use the wrong domain....

DEBUG: Starting new HTTP connection (1): readcomiconline.to:80
DEBUG: http://readcomiconline.to:80 "GET /Comic/Cyrus-Perkins-and-the-Haunted-Taxicab/TPB?id=170226 HTTP/1.1" 301 None

**Comment by Xonshiz** [comment]
Hmm that's weird... I did download a comic strip from readcomiconline.ru before checking in the code and it downloaded everything just fine. Why would it switch the domain to ".to"... A bit busy with my 9-5, will take a look at this over the weekend. Meanwhile, could you try to download from reacomiconline.ru and see if it's working fine or it's causing the same issue?

**Comment by StrangeDOS** [comment]
I'll poke at it some more and let you know what I find out :)

**Comment by Xonshiz** [comment]
sounds great. thanks! :)

**Comment by Xonshiz** [comment]
Same as #299
