### ISSUE TITLE
Cannot run from docker

### ISSUE THREAD

**Issue by StefanUlbrich** [Xonshiz/comic-dl#294]
Hi,

I followed the instruction for building the docker image.

When I run the alias, I get the following error:

```
Traceback (most recent call last):
  File "/usr/local/bin/comic_dl", line 10, in <module>
    from comic_dl.__version__ import __version__
  File "/opt/comic-dl/comic_dl/comic_dl.py", line 6, in <module>
    from .__version__ import __version__
ImportError: attempted relative import with no known parent package
```

Any idea what could cause the issue? Thanks

**Comment by Xonshiz** [comment]
Thanks a ton Stefan! Just merged that fix :)
P.S: Not on vacation, just busy with some work hahaha.
