### ISSUE TITLE
Windows Binary can't connect to db

### ISSUE THREAD

**Issue by kfung21** [Xonshiz/comic-dl#297]
Just downloaded the binary onto Win 10 desktop and tried to search as well as the suggested default command line input. Nothing seems to work and I opened cmd with admin rights. Please help

C:\Users\kevtf\OneDrive\Desktop\Programs\comic_dl>comic_dl.exe -i "https://readcomicsonline.ru/comic/irredeemable-omnibus-2012"
Fooling CloudFlare...Please Wait...
Total Time Taken To Complete : 0.3593170642852783

C:\Users\kevtf\OneDrive\Desktop\Programs\comic_dl>comic_dl.exe -find "One Piece"
Searching for One Piece in the Database...
Total Time Taken To Search : 0.0
API Provided By Manga Eden : http://www.mangaeden.co

Manga_Eden_Data.json file is empty

[Error_Log.log](https://github.com/Xonshiz/comic-dl/files/7371176/Error_Log.log)
m/

**Comment by Xonshiz** [comment]
Same as #299
