### ISSUE TITLE
new feature request ...... convert existing cbr or cbz files to pdf

### ISSUE THREAD

**Issue by bajechele** [Xonshiz/comic-dl#298]
hi xonshiz i came to know about this great tool somedays ago and i used it ... this tool is amazing it get the job done most time ....sometime it gives certain error where it failed to download couple of images and then showed some bad mac or some error but it worked most of the time... so when i was using it i thought if it can convert cbr cbz to pdf would be amazing coz then we can really read comics on mobile devices without even downloading or sideloading any app for cbr cbz ...... since this tool can already convert downloaded images to pdf ,cbr ,cbz i guess this tool can easily convert downloaded files with a lil help.....

**Comment by Xonshiz** [comment]
Hey thanks for the info, but still not sure of what you exactly want to achieve.
Are you saying you want this tool to convert already downloaded CBZ files into PDF?

**Comment by bajechele** [comment]
yes ....i have some cbr cbz files that i collected over time so if this tool can convert them to pdf would be more than happy to carry them over on my phone and can read them with out downloading or sideloading any app

**Comment by Xonshiz** [comment]
That seems like the functionality of a script/application of its own. This tool is specifically built for downloading comics/manga and converting them.
But, sure I'll try to take a look into this thing.

**Comment by darodi** [comment]
if you don't want to reinvent the wheel

https://github.com/phdesign/comic2pdf
