### ISSUE TITLE
Downloading whole range of comics

### ISSUE THREAD

**Issue by ATran001** [Xonshiz/comic-dl#300]
How do I download the whole range of comics on a site? I tried downloading via the link at the bottom but it returned nothing. When I download individually, the command seem to work.

Example.:
comic_dl.exe -i "https://readcomicsonline.ru/comic/xmen-2021/"

**Comment by Xonshiz** [comment]
What you're asking is already written in detail in the read me file. Please look at the `--range` option in the [List Of Arguments Section](https://github.com/Xonshiz/comic-dl#list-of-arguments).

Closing this, as this is already mentioned in readme file.
