### ISSUE TITLE
Error downloading

### ISSUE THREAD

**Issue by Getty-13** [Xonshiz/comic-dl#307]
![image](https://user-images.githubusercontent.com/55208935/163345744-2a679efa-eb32-401c-9d96-e999dfb321b6.png)
It is showing error 403 for trying to download comics from readcomiconline.li 

or this from comicextra.com
![image](https://user-images.githubusercontent.com/55208935/163346053-90ef9498-8617-4ce0-8e54-400bb69f403a.png)

**Comment by Xonshiz** [comment]
closing because similar to #299
