### ISSUE TITLE
[BUG] docker armv7 libjpeg.so.62  No such file or directory

### ISSUE THREAD

**Issue by Generator** [Xonshiz/comic-dl#310]
## Description
Running docker image on armv7 with [recommended alias](https://github.com/Xonshiz/comic-dl#docker), on armv7 end with error ```ImportError: libjpeg.so.62: cannot open shared object file: No such file or directory``` 

Tested on amd64, downloads the comics without issues.

output:
```
comic_dl -i "https://www.comicextra.com/comic/zero-hour-crisis-in-time" --convert cbz --verbose
Traceback (most recent call last):
  File "/opt/comic-dl/cli.py", line 2, in <module>
    from comic_dl.__main__ import main
  File "/opt/comic-dl/comic_dl/__main__.py", line 12, in <module>
    from comic_dl.manga_eden import *
  File "/opt/comic-dl/comic_dl/manga_eden/__init__.py", line 4, in <module>
    from . import mangaChapterDownload
  File "/opt/comic-dl/comic_dl/manga_eden/mangaChapterDownload.py", line 9, in <module>
    from comic_dl import globalFunctions
  File "/opt/comic-dl/comic_dl/globalFunctions.py", line 14, in <module>
    import img2pdf
  File "/usr/local/lib/python3.8/site-packages/img2pdf.py", line 25, in <module>
    from PIL import Image, TiffImagePlugin, GifImagePlugin
  File "/usr/local/lib/python3.8/site-packages/PIL/Image.py", line 132, in <module>
    from . import _imaging as core
ImportError: libjpeg.so.62: cannot open shared object file: No such file or directory
```

### Possible fix
Missing dependency ```libjpeg62-turbo``` (Debian Buster)

**Comment by Xonshiz** [comment]
Gotta check that.
@darodi any clue what might be happening here?

**Comment by darodi** [comment]
@Xonshiz 

I fixed the dependency issue on the base docker image on arm*.
github is building the last image. It takes 2-3hours to build.
https://github.com/darodi/docker-py3.8-slim-buster-pikepdf/pkgs/container/docker-py3.8-slim-buster-pikepdf

Once available, you can change https://github.com/Xonshiz/comic-dl/blob/master/comic_dl/__version__.py
for example to trigger a new docker build and push of comic-dl

**Comment by Xonshiz** [comment]
Amazing. I'll push an update. Thanks man!

**Comment by darodi** [comment]
There was a timeout during a part of the build.
The build has been relaunched.
Let's wait and see.

**Comment by darodi** [comment]
It was long but the build is now finally done.

**Comment by Xonshiz** [comment]
I didn't get time to add something worth in the push. I'll create a push by tomorrow most probably along with this.

**Comment by Xonshiz** [comment]
I've triggered a build for this. @Generator , please do try again and let us know. Feel free to re-open if the issue still persists.
Thanks.
