### ISSUE TITLE
Problem with packaging it in the AUR.

### ISSUE THREAD

**Issue by patlefort** [Xonshiz/comic-dl#312]
AUR package: https://aur.archlinux.org/packages/comic-dl

But trying to run it result in the following error:

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/comic_dl/__main__.py", line 10, in <module>
    from comic_dl.__version__ import __version__
  File "/usr/lib/python3.10/site-packages/comic_dl/comic_dl.py", line 6, in <module>
    from .__version__ import __version__
ImportError: attempted relative import with no known parent package
```

It used to work. Is it a change in python 3.10?

**Comment by Xonshiz** [comment]
If you see, that package was last updated in 2021 and I am not the one who published it.
There are some issues with relative import and to get around that, I've updated the instructions in the readme. That'll be the "new" way for a while.

If you're fetching this tool from third-party sources where I'm not the author, I can't help that out. I'd advise that you use the "Linux" binary available in the latest release section. Or, you could go through the readme and follow the new instructions.
