### ISSUE TITLE
ImportError: attempted relative import with no known parent package

### ISSUE THREAD

**Issue by kgoldmann** [Xonshiz/comic-dl#315]
When trying to run "python3 __main__.py" in the comic_dl directory on the macOS Terminal, I'm encountering the following error:

Traceback (most recent call last):
  File "/Users/username/Downloads/comic-dl-master/comic_dl/__main__.py", line 10, in <module>
    from comic_dl.__version__ import __version__
  File "/Users/username/Downloads/comic-dl-master/comic_dl/comic_dl.py", line 6, in <module>
    from .__version__ import __version__
ImportError: attempted relative import with no known parent package

Am I using the wrong syntax?

**Comment by darodi** [comment]
@kgoldmann 

use [/Users/username/Downloads/comic-dl-master/cli.py](https://github.com/Xonshiz/comic-dl/blob/master/cli.py) instead

**Comment by kgoldmann** [comment]
@darodi Thanks for this. cli.py worked for me, though any readcomiconline.li URLs just return 403 error. Maybe an issue with Cloudflare bypassing.

How does one use the OSX release?

**Comment by darodi** [comment]
@kgoldmann 
> ... any readcomiconline.li URLs just return 403 error. Maybe an issue with Cloudflare bypassing.

see
- https://github.com/Xonshiz/comic-dl/issues/314
- https://github.com/Xonshiz/comic-dl#notes
- https://github.com/Xonshiz/comic-dl/issues/299

> 
> How does one use the OSX release?

same way : 
https://github.com/Xonshiz/comic-dl#list-of-arguments

**Comment by Xonshiz** [comment]
Looks like that OSX release might have to go because of Apple's new restrictions of running external executables. Use Python for now on OSX as well, please

Closing this as Darodi already mentioned every required info. Thanks again, Darodi :)
