### ISSUE TITLE
No download with binary

### ISSUE THREAD

**Issue by StrangeDOS** [Xonshiz/comic-dl#321]
Hi! I tried the latest binary and while it seemed to be connecting, it isn't downloading.

C:\Program Files\nodejs>comic_dl.exe -i https://readcomiconline.li/Comic/Astonisher
Fooling CloudFlare...Please Wait...
Total Time Taken To Complete : 0.7502410411834717

C:\Program Files\nodejs>comic_dl.exe -i https://readcomiconline.li/Comic/Astonisher --d c:\ComicDownload
Fooling CloudFlare...Please Wait...
Total Time Taken To Complete : 0.6726968288421631

C:\Program Files\nodejs>comic_dl --version
2022.04.23

**Comment by StrangeDOS** [comment]
Forgot the error log...
DEBUG: Arguments Provided : Namespace(version=False, sorting=None, auto=False, config=False, download_directory=['C:\\Program Files\\nodejs'], range='All', convert=None, keep=['True'], quality='True', input=['https://readcomiconline.li/Comic/Astonisher'], cookie=None, comic=False, search_comic=None, comic_info=None, update=None, print_index=False, search=None, manga_language='0', skip_cache='0', chapter_id=None, page_id=None, force_download=False, password=['None'], username=['None'], verbose=True)
DEBUG: Operating System : Windows - 10 - 10.0.22000
DEBUG: Python Version : 3.9.12 (64bit)
DEBUG: Script Version : 2022.04.23
DEBUG: Comic Url : https://readcomiconline.li/Comic/Astonisher
DEBUG: Selected Domain : readcomiconline.li
DEBUG: Starting new HTTPS connection (1): readcomiconline.li:443
DEBUG: https://readcomiconline.li:443 "GET /Comic/Astonisher HTTP/1.1" 200 None
DEBUG: Encoding detection: utf_8 will be used as a fallback match
DEBUG: Encoding detection: Found utf_8 as plausible (best-candidate) for content. With 0 alternatives.
DEBUG: All Links : []

**Comment by Xonshiz** [comment]
I'll take a look at it over this weekend (probably) ;)

**Comment by Xonshiz** [comment]
Oh wait, this is RCO. Please refer to #299

**Comment by StrangeDOS** [comment]
I'm not seeing a 403.  But I did review #299 .  Looks like that problem is just with RCO.  So I tried a different site.  Not working there either.

C:\Program Files\nodejs>comic_dl.exe -i "https://readcomiconline.li/Comic/Star-Wars-Darth-Vader-and-the-Lost-Command-2011/Issue-1?id=74747#1"
Fooling CloudFlare...Please Wait...
[]
[Comic-dl] Done : Star Wars Darth Vader And The Lost Command 2011 [Issue - 1] : : 0image(s) [00:00, ?image(s)/s]
Total Time Taken To Complete : 0.7943041324615479

C:\Program Files\nodejs>comic_dl -i https://www.comicextra.com/comic/marvel-action-captain-marvel-2021
Http Error:
Http Error:
Http Error:
Http Error:
Http Error:
Http Error:
Http Error:
Http Error:
Http Error:
Http Error:
Http Error:
Http Error:
Http Error:
Http Error:
Http Error:
Http Error:
Http Error:
Http Error:
Http Error:
Http Error:
Http Error:
Http Error:
[Comic-dl] Error : Marvel Action Captain Marvel 2021 [1] - 'HTTPError' object has no attribute 'message' :   0%| | 0/22
ERROR:root:Error downloading : https://www.comicextra.com/marvel-action-captain-marvel-2021/chapter-1/full
Total Time Taken To Complete : 5.773374557495117
