### ISSUE TITLE
add support for https://digitalcomicmuseum.com

### ISSUE THREAD

**Issue by LegalizeAdulthood** [Xonshiz/comic-dl#325]
thanks

**Comment by Xonshiz** [comment]
Please put proper information regarding the request.
Some links to the chapter and chapter list are appreciated. Closing this for lack of information.

**Comment by LegalizeAdulthood** [comment]
I thought it was self evident if you browse the URL.  They have a link per title and within each title have a link per issue and the "preview" link on each issue page takes you to a click-through reader of the images.

**Comment by LegalizeAdulthood** [comment]
Well I guess they allow downloading with a free registration, but would be nice to support downloading without having to create an account.

**Comment by Xonshiz** [comment]
Hey, if you cannot take your time to properly include the details, why should anyone be bothered to implement that?
Please follow how this request has been raised: #284 
I'll reopen once the information has been properly laid out.

Thanks
