### ISSUE TITLE
Cannot seem to download anything - Screens.

### ISSUE THREAD

**Issue by DarklySatanic** [Xonshiz/comic-dl#328]
Hey guys! 
So I've used this before, and it went fine. However, for some reason, I'm stuck and would love some tips. Here's the list of what I did, in order, having followed the instructions.

1. Downloaded and installed node.js into C:\Windows.
2. 2. Downloaded the repository, installed that onto my C folder.
3. Downloaded binary, comic-dll.exe and put it into a random folder by itself.
4. 'Open Command Window' is not showing up when I hold down shift and click. Used 'Open Powershell Window Here'.
5. Used the example: "comic_dl.exe -i "https://readcomicsonline.ru/comic/irredeemable-omnibus-2012" failed. Tried ".\comic_dl.exe -i "https://readcomicsonline.ru/comic/irredeemable-omnibus-2012". Worked.

But...

7. "Fooling CloudFlare...Please Wait...
Total Time Taken To Complete : 0.7655007839202881
PS C:\Users\Shadow\Downloads\Programs>"

There is no indication that anything was downloaded. I cannot see them in any folders.

Please help if you can!
Trying to 'help myself' here. Have moved the .exe file into the comic-dl-master folder's main directory.
Got the 'configure' screen to work, where it asks for the password and username if any, before saying 'clear isn't a valid something'

![image](https://user-images.githubusercontent.com/115671373/195462766-8a5375cc-b32c-4126-a7a3-6614e38244f8.png)
![image](https://user-images.githubusercontent.com/115671373/195462863-7b1242cd-e016-48c3-a454-33a2aea2f0d9.png)
![image](https://user-images.githubusercontent.com/115671373/195463293-65e2695d-74da-46e0-8f99-673343bfc773.png)

and then...

![image](https://user-images.githubusercontent.com/115671373/195463668-a04d9108-ba15-45b9-b50a-89e25d443416.png)

The 522 error is odd, since I didn't even specify a website the second time, and the website I was trying *is* working. Just not with this program anymore, I guess?

With the 'c' command:

![image](https://user-images.githubusercontent.com/115671373/195464430-af651fb4-cac3-478e-90f9-5cacfcf70fc1.png)

Lastly...

![image](https://user-images.githubusercontent.com/115671373/195465027-cfd4562f-d463-4979-9698-37832588a1ef.png)
![image](https://user-images.githubusercontent.com/115671373/195465216-a41e7eb5-48f3-45aa-be10-044d0920b1b2.png)

**Comment by DarklySatanic** [comment]
![image](https://user-images.githubusercontent.com/115671373/195467694-d894333d-8b26-4836-9f98-0b3371a1c3dd.png)
Just tried this. A step forward.

I'm guessing any of the readcomiconline domains are no longer supported and we can only download manga..

I actually had used the readcomiconline downloader about 2 years ago without an issue.

**Comment by DarklySatanic** [comment]
![image](https://user-images.githubusercontent.com/115671373/195475521-1288d08c-b2b3-47aa-b35a-f23bc98cd684.png)
One step closer, if I search for a specific issue.

**Comment by Xonshiz** [comment]
Since this is related to ReadComicsOnline, linking this with #299 and closing this.
RCO isn't working and it's a known issue, more details on the issue I just linked.
