### ISSUE TITLE
Another error regarding conversion

### ISSUE THREAD

**Issue by Baidya99** [Xonshiz/comic-dl#33]
![capture](https://user-images.githubusercontent.com/16690760/27944128-4f6e4a86-6302-11e7-8217-310e4a9ad7bd.PNG)

**Comment by Xonshiz** [comment]
uh, could you please for Christ's sake check the READ ME and post accordingly? Screenshot doesn't tell me anything. Error logs does. Btw, seems like you're passing wrong arguments.

I'm closing this issue for lack of information. Reply to this issue properly, as mentioned in the read me and I'll re-open accordingly.

**Comment by Baidya99** [comment]
Sorry

**Comment by Baidya99** [comment]
I think some dependencies are required for the pdf conversion in the windows binary hence the error.
[Error_Log](https://gist.github.com/Baidya99/4edaa343700473e423280975fa3e45fc)

**Comment by beshoyholmes** [comment]
I'm having an issue that when i open comic_dl.exe (with or without the shift+right-click thing) it opens for a few seconds and then without typing a letter it closes immediately

**Comment by Baidya99** [comment]
It is a command line tool to use it follow [usage](https://github.com/Xonshiz/comic-dl#windows) instructions.
