### ISSUE TITLE
ReadComicOnline Downloader non-Github Alternate.

### ISSUE THREAD

**Issue by DarklySatanic** [Xonshiz/comic-dl#349]
Hey guys, here's a NON-Github Alternate to Comic-DL. Well, in truth, I did get the file from here, but python isn't required.

It's called Hakuneko, and it is a windows binary file. I won't link it here, because I got on the other individual for linking his work here, and I would feel like a hypocrite. 

It's legit and straight-forward, and here is a screenshot:

<img width="1274" alt="image" src="https://github.com/Xonshiz/comic-dl/assets/115671373/85c9cf17-f0ef-454c-9c8f-4460f88d5f0f">
To explain how I went from there to here:
<img width="1273" alt="image" src="https://github.com/Xonshiz/comic-dl/assets/115671373/e01fe869-f507-452e-a146-ffe573b58650">

1. Where it has the plug icon aka the Connector, Select 'ReadComicOnline.li (Kiss Comic). 
2. You can leave the Search field blank, or select a specific comic. 
3. I left it blank, so it took about 20 minutes to populate the fields. Keep in mind that ReadComicOnline.li has over 900 pages, and each page was added to the program. 
4. I clicked my selection, "X-Men: Dark Phoenix Saga". As you can see, it has only one 'Chapter', which is the TPB (which matches the website perfectly). 
5. Click the 'Download' icon, it looks like the cloud symbol. 
6. By default, it will download to a 'Manga' folder in 'My Documents'.
7. From there, right-click the folder within 'Manga'. For me, it was 'TPB'. Then choose to 'add to archive'. I named it "X-Men The Dark Phoenix Saga.cbr".
8. Rinse and repeat with your choices.

While others may have been more partial to the ReadComicOnline-DL file that the gentleman added here (I am a complete dunce with Python, so I unfortunately require a lot more handholding!) this is mostly for others who may not be as familiar with Python, or maybe don't like having to install the dependencies it requires.

This will, I hope, satisfy us until Xonshiz is able to resume his wonderful work on this project. 

Some caveats:

1. From my personal experience, you must click each 'cloud' icon to download the files, there doesn't seem to be a bulk setting at this time. Edit: NOT ACCURATE. There is a Download All button near the 'Chapter List' title.
2. Downloads won't be staggeringly fast, but not terrible.
3. For large series, and if you choose to download a full series of 500+ issues, you may loathe having to archive each file specifically. What I personally do is I grab about 20-30 of them, and zip them into one archive, then rinse and repeat. 
4. This is NOT immune to the Cloudflare issue, but there will be a popup box within the app itself that allows you to click the capcha. 
I strongly prefer Xonshiz's version of this type of app, so will only be using it until he is able to resume his work.

**Comment by darodi** [comment]
> Hey guys, here's a NON-Github Alternate to Comic-DL.

?! 
https://github.com/manga-download/hakuneko :wink:

**Comment by Xonshiz** [comment]
This looks good. Thanks for sharing this one, it's okay to link other tools that work. Just don't be an arse ;)
This looks promising and is much easier to use because of the GUI.
Honestly, I can't promise I'll ever get anything updated in comic_dl, but that shouldn't limit people from having an easy way to download and read comics/manga.

I'll close and lock this conversation as I think this doesn't require further discussion.
Again, thanks for sharing this tool.
