### ISSUE TITLE
windows binary naming

### ISSUE THREAD

**Issue by redranamber** [Xonshiz/comic-dl#37]
The binary is named comic_dl.exe but in the readme it gives the command as comic-dl.exe -i \<URL TO THE COMIC> which won't work due to the different names.  This could cause some confusion so I suggest renaming the binary to comic-dl.exe to make it consistent.

**Comment by Baidya99** [comment]
Yeah and there is also the argument `--conversion` which actually should be `--convert`

**Comment by Xonshiz** [comment]
Cool, I'll update this all next week. :)

**Comment by Xonshiz** [comment]
This should be fixed now.
