### ISSUE TITLE
readcomiconline.to ERROR

### ISSUE THREAD

**Issue by zeus00786** [Xonshiz/comic-dl#38]
On downloading comic from readcomiconline.to I get nothing but a blank folder.

Output:
`comic.exe -i http://readcomiconline.to/Comic/Spider-Man-2099-2014/Issue-1?id=30174

     =====================================================================
                       Manga Name : Spider Man 2099 2014
                           Chapter Number - Issue - 1
     =====================================================================

Total Time Taken To Complete : 10.6209998131`

**Comment by jaxxa** [comment]
I had that issue intermittently. Not certain if it is just something that randomly changes on their side, or if it is an anti downloading system.

Had you downloaded much from that site before?

**Comment by zeus00786** [comment]
Nope I downloaded some 60 issues of different comic and gave a gap of two days. The website is opening but cant download via CLI

**Comment by Xonshiz** [comment]
Checked this url on my side and everything's working just fine. Closing this issue because working on my side and you have not provided any verbose log.
