### ISSUE TITLE
CAPTCHA / reCAPTCHA

### ISSUE THREAD

**Issue by ComputerCommander** [Xonshiz/comic-dl#40]
The Website (http://readcomiconline.to) seems to have added CAPTCHA / reCAPTCHA to their sight making this tool unusable with their website.

**Comment by Xonshiz** [comment]
Give it some time, try to download again. Happens when you hit the website too often.

Open your browser, navigate to the website, solve the captcha, if any.
Don't visit the website for at least 24 Hours and then try again with the script.
