### ISSUE TITLE
Question/Request

### ISSUE THREAD

**Issue by ShadowStriker** [Xonshiz/comic-dl#41]
When using the Windows Binary I right click and "Open command window here" then put in comic_dl.exe -i (site)

Is there a way to write the syntax so that instead of opening command window then comic_dl.exe -i (site), I could instead write everything with the site and click it like an executable? (Purpose? Create an Excel with all the pages I want to use the downloader on, then write the syntax with those pages added in, and click each cell to execute just that page download.)

Request:
A Windows *bong* sound when finished downloading

A list/log of pages that didn't download (I sometimes get a log when this happens... am I just stupid or does it not specify which pages?)

LOVE Comic_dl! THANK YOU FOR CREATING THIS! :D

**Comment by Xonshiz** [comment]
- A Windows bong sound when finished downloading.

**Comment by Xonshiz** [comment]
`A list/log of pages that didn't download.`

Just checked that the tool already prints it on the screen that the file was skipped/couldn't be downloaded.
