### ISSUE TITLE
Original image resolution

### ISSUE THREAD

**Issue by apokolipsnow** [Xonshiz/comic-dl#42]
I've noticed that the .jpg images generated from readcomiconline are of a lower resolution compared to simply right-clicking as "saving as", is there a component of comic-dl which is responsible for this compression, and is it possible to disable this...?

**Comment by Xonshiz** [comment]
Hey,

No, there's nothing in comic_dl that does this. However, if you've noticed, there are two types of images in ReadComic... High Res and Low Res.

The script downloads either of them. I have some work till September, I'll fix this thing after that :)

**Comment by apokolipsnow** [comment]
I should have copped the low/high res thing, apologies...  Hopefully it's not too much work to introduce the fix, and thanks for taking the time!  ^_^

**Comment by Xonshiz** [comment]
I've made few changes.
1.) By default, the downloader will download High Resolution Images from readcomiconline.to.

2.) Added a new option/argument to let the user decide the quality they want.

Check the readme for further information on how to use the argument(s).

Closing this issue now!

**Comment by apokolipsnow** [comment]
Thank you so much!  I don't want to be a pain, but I've found for a few titles it still opts for the low res preferentially over the high res.  I read your instructions in that one can specify a lower resolution, but would a keyword like "high" work?

**Comment by Xonshiz** [comment]
Hey, could you please share those links? If you want to download HQ, you don't need to pass anything. It'll download HQ by default. There might be images where the HQ is not available. Please share those URLs that are downloading LQ instead of HQ.

**Comment by apokolipsnow** [comment]
Hi, thanks for getting back so quickly.  The first two I came across were the following:

http://readcomiconline.to/Comic/Kingdom-Come-1996
http://readcomiconline.to/Comic/Green-Lantern-2005

There are HQ pages available, but it's opting for the LQ versions.  I'm not doing anything fancy, just the basic .exe -i with the links as shown above!  :)

**Comment by Xonshiz** [comment]
Ah, okay.. found the issue. RCO peeps need to be structured for real. I'll update this fix in a few minutes.. :)

**Comment by Xonshiz** [comment]
Alright, fixed and checked. Shouldn't pose any problems like this now. Please grab the [latest windows binary](https://github.com/Xonshiz/comic-dl/releases/latest) or the python source code and try again.
