### ISSUE TITLE
MangaReader

### ISSUE THREAD

**Issue by jimmy213** [Xonshiz/comic-dl#43]
Could it be possible to add http://www.mangareader.net/ to the supported sites?

Thanks for the script btw.

**Comment by Xonshiz** [comment]
Yep sure. I'll try to add it by the end of this month. I'm a little busy with work right now.

**Comment by jimmy213** [comment]
Nice. Thank you.

**Comment by Xonshiz** [comment]
Site support added. Windows binary will be released soon.

**Comment by jimmy213** [comment]
Thanks again.
