### ISSUE TITLE
Windows Binary Version is not working with Windows Powershell

### ISSUE THREAD

**Issue by Armiger-Exvius** [Xonshiz/comic-dl#46]
My new computer has Powershell instead of Command Prompt and whenever I tried to use the command code for the application I end up getting this message.

![image](https://user-images.githubusercontent.com/32207589/30763110-c10230e4-9fb2-11e7-917f-fabe5a0e891b.png)

Is there any way to fix this or change Powershell back into Command Prompt without causing any damage to my computer?

**Comment by Xonshiz** [comment]
Hello,

Windows 10 has "PowerShell" in the "Context Menu" when you hold down shift. Powershell is DOS like.
To run any executable via powershell, you must append ".\" in the beginning.

So, for example : 

Your command in command prompt : 

`
comic_dl.exe --version
`

Your command in Powershell : 

`
.\comic_dl.exe --version
`

Also, next time please do read the error/warning/suggestion that is displayed in your Powershell. It's recommending you to append ".\" in the beginning. This should fix your issue.

Let me know if you still face problems.
