### ISSUE TITLE
readcomiconline.to not working

### ISSUE THREAD

**Issue by jmans25** [Xonshiz/comic-dl#47]
The following site wasn't working in  v2017.09.21: http://readcomiconline.to
Here is the command I used to download "Watchmen"

`comic_dl.exe -i "http://readcomiconline.to/Comic/Watchmen/Issue-2?id=14880&quality=hq" -v`

Here is the error_log file:
```
DEBUG: Arguments Provided : Namespace(convert=None, download_directory=None, input=['http://readcomiconline.to/Comic/Watchmen/Issue-2?id=14880&quality=hq'], keep='True', quality='True', range='All', sorting=None, verbose=True, version=False)
DEBUG: Operating System : Windows - 10 - 10.0.15063
DEBUG: Python Version : 2.7.13 (32bit)
DEBUG: Comic Url : http://readcomiconline.to/Comic/Watchmen/Issue-2?id=14880&quality=hq
DEBUG: Selected Domain : readcomiconline.to
DEBUG: Starting new HTTP connection (1): readcomiconline.to
DEBUG: http://readcomiconline.to:80 "GET /Comic/Watchmen/Issue-2?id=14880&quality=hq HTTP/1.1" 503 None
DEBUG: Resetting dropped connection: readcomiconline.to
DEBUG: http://readcomiconline.to:80 "GET /cdn-cgi/l/chk_jschl?jschl_answer=5262&jschl_vc=74df9b5ac34f304ba6182c65f1ffd429&pass=1506195036.605-mHvuY%2FgWuW HTTP/1.1" 302 165
DEBUG: http://readcomiconline.to:80 "GET /Comic/Watchmen/Issue-2?id=14880&quality=hq HTTP/1.1" 200 None
DEBUG: All Links : []
```

Here is the output on the console:
```
***Starting the script in Verbose Mode***

Finished Downloading
Total Time Taken To Complete : 6.33700013161
```
However, nothing was downloaded. 

With an older version of the script (on my other computer, not sure which version, is there a way I can find out from the tool itself?) I would use the same command, and each page would show separate download bars on the console. I recently tried that older copy, and it still worked. 

I tried using the '--quality high' flags, removing the quotes from URL, removing the "http://", and removing the parameters `?id=14880&quality=hq HTTP/1.1` from the URL. Nothing fixed it. 

Is there anything I am doing wrong with the current version?

Thanks

**Comment by Xonshiz** [comment]
This has been fixed. I messed up in the last update, my bad.

Anyways, you can check the application version by passing "--version" argument.

`comic_dl.exe --version`

and it'll print the version.

Please check the [latest release](https://github.com/Xonshiz/comic-dl/releases/latest) for the fixed update. Let me know if the problem still persists.
