### ISSUE TITLE
'Failed to execute script'

### ISSUE THREAD

**Issue by vomov** [Xonshiz/comic-dl#5]
It would seem that the latest version does not want to start. Using -v it gives me the following in the error log:
`DEBUG: You have successfully set the Debugging On.
DEBUG: Arguments Provided : Namespace(about=False, input=['http://kissmanga.com/Manga/Gunnm-Kasei-Senki'], password='None', sorting=None, username='None', verbose=True, version=False)
DEBUG: Operating System : Windows - 7 - 6.1.7601
DEBUG: Python Version : 3.5.2 (32bit)`
And then nothing else.

However, the command window states this:
`D:\com>comic_dl.exe -v -i www.kissmanga.com/Manga/Gunnm-Kasei-Senki
Traceback (most recent call last):
  File "comic_dl\comic_dl.py", line 83, in <module>
  File "comic_dl\comic_dl.py", line 78, in main
TypeError: 'NoneType' object is not subscriptable
Failed to execute script comic_dl`

`D:\com>comic_dl.exe  -i http://kissmanga.com/Manga/Gunnm-Kasei-Senki
Traceback (most recent call last):
  File "comic_dl\comic_dl.py", line 83, in <module>
  File "comic_dl\comic_dl.py", line 78, in main
TypeError: 'NoneType' object is not subscriptable
Failed to execute script comic_dl`

**Comment by Xonshiz** [comment]
Yes, I just ran into the issue myself. I messed up in the latest release. You have to pass another argument `--sorting` currently. It shouldn't be mandatory, but I guess I missed something while programming this. So, for now, you have to add one more argument like `--sorting asc` or `--sorting desc` and it should work. I'll fix this over this weekend.

**Comment by Xonshiz** [comment]
Got time, fixed it. Should be fine now :)
