### ISSUE TITLE
Download Range

### ISSUE THREAD

**Issue by ducle2502** [Xonshiz/comic-dl#50]
Please add the function to download from a specific chapter to the end of a series without having to input an end number. I noticed the script checks if the range I input was correct or not so I figured this feature can be added to the script. Thank you very much for your work.

**Comment by Xonshiz** [comment]
I really don't see the usage of this case. I mean, if you're entering the starting chapter number, then you might as well add the ending number.I'll keep this one on the lowest priority for now.

**Comment by Xonshiz** [comment]
PR #56 added this feature. @Tyroc thanks :)
