### ISSUE TITLE
Download quality not used

### ISSUE THREAD

**Issue by dsanchezseco** [Xonshiz/comic-dl#51]
It's seems that is a ctrl+c/v typo -> comic_dl.py line 69

Here's the snippet of code.
```
[...]
            if not args.convert:
                args.convert = ["None"]
            if not args.keep:
                args.keep = ["True"]
            if not args.keep:
                args.keep = ["Best"]

            start_time = time.time()
[...]
```

**Comment by Xonshiz** [comment]
Nice catch! I'll fix this up tomorrow.

**Comment by dsanchezseco** [comment]
maybe i do a pull request later. i'm also trying to figure whats the problem with conversion on mac/linux. #bugIncoming

**Comment by Xonshiz** [comment]
That'll be great then. Damn conversion not working on mac/linux? I think I need to set up some virtual env here on my end as well.

**Comment by dsanchezseco** [comment]
The principal suspect is 
```
        path_breaker = str(old_path).split("\\")
``` mac/linux use `/` as separator opposite to `\` of Win

**Comment by Xonshiz** [comment]
Ah, I see. I had my doubts while putting those in the code. Cross-platform compatibility can be a bitch sometimes. I'll look into this later tomorrow and try to fix it quick...

**Comment by Xonshiz** [comment]
Thanks for the PR, @dsanchezseco . Please make a new Issue for  the path problem.

**Comment by dsanchezseco** [comment]
I'm on it
