### ISSUE TITLE
http://readcomicbooksonline.net/

### ISSUE THREAD

**Issue by SalviGG** [Xonshiz/comic-dl#57]
Hello, just found out about this tool.  Is there any chance, if it's not already in the plans, to add http://readcomicbooksonline.net/  to the supported sites?

Thanks, awesome script.

**Comment by Xonshiz** [comment]
Hey! Sure, I'll look into it and will try to add it by the end of this month :)

**Comment by SalviGG** [comment]
Great! thanks!

**Comment by Xonshiz** [comment]
Support has been added for this one. Get the updated version and check on your end.
