### ISSUE TITLE
'readType' is not recognized as an internal or external command?

### ISSUE THREAD

**Issue by cacamarena42** [Xonshiz/comic-dl#59]
First time using this so I don't know if I used the arguments correctly.

Command I gave:  comic_dl.exe -v -i http://readcomiconline.to/Comic/Batman-2016/Issue-1?id=63467&readType=0 --quality High --convert cbz

Expected behavior:  Downloads the images in high quality and converts it into a cbz file.

Actual behavior:  Downloaded the images only and then says 'readType' is not recognized as an internal or external command, operable program or batch file.

[https://pastebin.com/800eDAU5](url)

**Comment by Xonshiz** [comment]
Hey! The script is just fine. However, there's an issue with your command. I'll try to explain : 

In a CMD, when you enter "&", it will break the command after it and consider it as another command.

So, when you give this "`comic_dl.exe -v -i http://readcomiconline.to/Comic/Batman-2016/Issue-1?id=63467&readType=0 --quality High --convert cbz`"

, it makes it this : 
"`comic_dl.exe -v -i http://readcomiconline.to/Comic/Batman-2016/Issue-1?id=63467`"

and then executes this : 
"`readType=0 --quality High --convert cbz`"

Get it? So, to fix it, you should put quotes around the url. Like this : 

`comic_dl.exe -v -i "http://readcomiconline.to/Comic/Batman-2016/Issue-1?id=63467&readType=0" --quality High --convert cbz`

**Comment by Xonshiz** [comment]
Besides, you don't need to put that `&readType=0` in the url. You could just provide this : `http://readcomiconline.to/Comic/Batman-2016/Issue-1?id=63467` and it'll work.

**Comment by cacamarena42** [comment]
oh ok! thank you very much!
