### ISSUE TITLE
[Error 3] The system cannot find the path specified: '' ?

### ISSUE THREAD

**Issue by cacamarena42** [Xonshiz/comic-dl#60]
Command I used: comic_dl.exe -i http://readcomiconline.to/Comic/Batman-2016/Issue-7?id=89390 --convert cbz --keep no

Expected: Downloads the comic and converts it to a cbz file without having to run the command twice

Actual: Downloads the comic, but something happens when creating the cbz file because I think it can't find the folder.

NOTE: This only happens when I download a new comic the first time around. For example, I download a new comic, gives me an error. Run the script again, works fine. I think it's because the folder has already been created from the first time around, which allows the second time to not give the error. I don't know if I'm doing something wrong or if this is a bug.

[EDIT] I guess I should also mention this too. This isn't too important, but in the second time around when using the script it says "Destination path '/[Comic book name].cbz' already exists". Not really an important thing, just wanted to mention it.

https://pastebin.com/mYnkfkpV

![image](https://user-images.githubusercontent.com/25369528/33951323-4a0bee94-dff4-11e7-824f-b06510eaf784.png)

**Comment by Xonshiz** [comment]
Thanks for reporting. I'll look into this :)
