### ISSUE TITLE
Using ranges on readcomiconline.to

### ISSUE THREAD

**Issue by fruitblood** [Xonshiz/comic-dl#61]
I wanted to tell you how much I love your script. I couldn't figure out how to get the Mac app up and running, but I did get the python script going on my Mac. I was able to successfully use ranges on omgbeaupeep, but not on readcomiconline. The URLs on that site are a bit more complex, so maybe it's not possible, but I'm just wondering if you know a trick to format the ranges properly to make them work for readcomiconline.

**Comment by Xonshiz** [comment]
Hey! Could you please respond according to the  steps and structure mentioned in the read me? Or refer to this : #60 

I need to know which command you issued and how you issued it.

**Comment by fruitblood** [comment]
Sorry I didn't include this last time. Here's an example of a command attempting to get the first ten issues of Spawn. It only yields the first issue.

> fruitbloodMBP:comic_dl fruitblood$ python __main__.py -dd /Users/fruitblood/Documents/Torrents/Comics/Spawn --range 1-10 --convert cbz --keep no --i http://readcomiconline.to/Comic/Spawn/Issue-1?id=20349
> 
> 
>      =====================================================================      
>                                Manga Name : Spawn                               
>                            Chapter Number - Issue - 1                           
>      =====================================================================
>      
> [Comic-dl] Downloading : 00.jpg
> [################################] 2110/2110 - 00:00:01
> [Comic-dl] Downloading : 01.jpg
> [################################] 455/455 - 00:00:00
> [Comic-dl] Downloading : 02.jpg
> [################################] 754/754 - 00:00:00
> [Comic-dl] Downloading : 03.jpg
> [################################] 891/891 - 00:00:00
> [Comic-dl] Downloading : 04.jpg
> [################################] 1176/1176 - 00:00:01
> [Comic-dl] Downloading : 05.jpg
> [################################] 1698/1698 - 00:00:03
> [Comic-dl] Downloading : 06.jpg
> [################################] 1865/1865 - 00:00:02
> [Comic-dl] Downloading : 07.jpg
> [################################] 1791/1791 - 00:00:01
> [Comic-dl] Downloading : 08.jpg
> [################################] 1193/1193 - 00:00:01
> [Comic-dl] Downloading : 09.jpg
> [################################] 3826/3826 - 00:00:01
> [Comic-dl] Downloading : 10.jpg
> [################################] 1416/1416 - 00:00:01
> [Comic-dl] Downloading : 11.jpg
> [################################] 1689/1689 - 00:00:02
> [Comic-dl] Downloading : 12.jpg
> [################################] 1826/1826 - 00:00:06
> [Comic-dl] Downloading : 13.jpg
> [################################] 1822/1822 - 00:00:01
> [Comic-dl] Downloading : 14.jpg
> [################################] 1293/1293 - 00:00:01
> [Comic-dl] Downloading : 15.jpg
> [################################] 1617/1617 - 00:00:01
> [Comic-dl] Downloading : 16.jpg
> [################################] 1640/1640 - 00:00:03
> [Comic-dl] Downloading : 17.jpg
> [################################] 1831/1831 - 00:00:03
> [Comic-dl] Downloading : 18.jpg
> [################################] 1085/1085 - 00:00:01
> [Comic-dl] Downloading : 19.jpg
> [################################] 1133/1133 - 00:00:01
> [Comic-dl] Downloading : 20.jpg
> [################################] 1957/1957 - 00:00:01
> [Comic-dl] Downloading : 21.jpg
> [################################] 1465/1465 - 00:00:01
> [Comic-dl] Downloading : 22.jpg
> [################################] 1701/1701 - 00:00:02
> [Comic-dl] Downloading : 23.jpg
> [################################] 27/27 - 00:00:01
> Cleaning Up...
> Deleted the files...
> Total Time Taken To Complete : 63.6579129696
> fruitbloodMBP:comic_dl fruitblood$
>

**Comment by fruitblood** [comment]
It looks like markdown changed the double underscores around "main" to bold. Probably should have pasted it as code.

**Comment by Xonshiz** [comment]
Cool, no problem. Will check it :)

**Comment by Xonshiz** [comment]
Okay, just checked your input command. First thing, you're not providing the proper URL for the chapter listing.You're giving the URL that points to a specific "Issue", rather the the "Comic Series" itself. So, instead of giving "http://readcomiconline.to/Comic/Spawn/Issue-1?id=20349", you should be giving "http://readcomiconline.to/Comic/Spawn".

I've pushed the fixed code for Python, you can grab that. I'll be adding the windows binary tomorrow for this update.
