### ISSUE TITLE
Website inclusion

### ISSUE THREAD

**Issue by ducle2502** [Xonshiz/comic-dl#62]
Hello! Can you include https://mangarock.com to the list of supported sites? 
Thank you!

**Comment by Xonshiz** [comment]
Yes, sure. Will  look into this. :)

**Comment by Xonshiz** [comment]
This will take some time. They have a custom Manga Reader on their website, which kind of makes it hard, because they're not serving the images directly.

**Comment by Xonshiz** [comment]
Support for MangaRock.com has been added! Please check it on your end.
