### ISSUE TITLE
Including readcomics.website

### ISSUE THREAD

**Issue by flo333** [Xonshiz/comic-dl#63]
Hello, great script! I've been using it for a while now. Do you think you could include www.readcomics.website? They have great grouping, making it really easy to find what you want (i.e. all DC Rebirth #1 stuff in one place: http://readcomics.website/comic/dc-comics-rebirth)

Thanks!

**Comment by Xonshiz** [comment]
Hey! Yes, sure, I'll look into it :)

**Comment by Xonshiz** [comment]
The support for this website has been added. You can download the latest update and check on your end.
