### ISSUE TITLE
Windows Binary giving an error

### ISSUE THREAD

**Issue by rawdpiper** [Xonshiz/comic-dl#64]
I made use of the windows binary and I'm getting this error as shown in the attached picture, I noticed that it just creates the folder and then nothing else.
![xonshiz](https://user-images.githubusercontent.com/22367812/34368728-5ef6d374-eab6-11e7-9078-f6fdabea25dd.jpg)

**Comment by rawdpiper** [comment]
My bad, I've resolved it. It seems go manga is not supported, it works fine with manga here.

**Comment by Xonshiz** [comment]
Gomanga is supported. I'm re-opening this issue to fix it.

**Comment by rawdpiper** [comment]
The same thing occurs with manga fox also

**Comment by Xonshiz** [comment]
Thanks for notifying. I'll fix this by tonight. I've fixed Gomanga on my end, will release a batch update fixing the MangaFox and #66 as well. Keep an eye out for an update!

**Comment by Xonshiz** [comment]
I've fixed the issue on GoManga and Python Source has been released, I'll fix MangaFox as well and then release the windows binary as well.

**Comment by Xonshiz** [comment]
Made a wrong commit. But, [this](https://github.com/Xonshiz/comic-dl/commit/4886184bd969d465abc265ef8149c09a70977b7a) fixes the issue with Mangafox as well.

**Comment by rawdpiper** [comment]
Mangafox still giving error. Using windows binary
![xonshiz](https://user-images.githubusercontent.com/22367812/34401021-9507d44a-eb97-11e7-87a8-734493c77ea0.jpg)
[Error_Log.log](https://github.com/Xonshiz/comic-dl/files/1590488/Error_Log.log)
