### ISSUE TITLE
Converting to pdf or cbz

### ISSUE THREAD

**Issue by rawdpiper** [Xonshiz/comic-dl#65]
the script works fine downloading the manga in  jpeg pictures but i'm trying to use the convert argument but i keep getting error
![xonshiz](https://user-images.githubusercontent.com/22367812/34369025-f0fdb13c-eab8-11e7-9db3-ff48de82ad56.jpg)

**Comment by Xonshiz** [comment]
You have an error in your command. you have added a colon ":" after convert. Remove it and it should work.

**Comment by rawdpiper** [comment]
Done. Thanks
