### ISSUE TITLE
Some Pages giving error 404

### ISSUE THREAD

**Issue by rawdpiper** [Xonshiz/comic-dl#66]
I'm downloading from manga reader and I'm getting error:404 for some of the pages in chapter 1 and 2, so i decided to check out the pages giving the error on my browser and they opened, didn't get any error
[Error_Log.log](https://github.com/Xonshiz/comic-dl/files/1588262/Error_Log.log)
Also noticed that the pages of the chapters downloaded doesn't tally with the page online
![xonshiz](https://user-images.githubusercontent.com/22367812/34369814-6abfcab8-eabf-11e7-8918-6895e23f2efe.jpg)
as shown from the attached picture, page 12 downloaded is page 34 online.

Also some pages are skipped.

**Comment by Xonshiz** [comment]
Please do leave the links to those manga chapters you've tried, as well.

**Comment by rawdpiper** [comment]
These are the links:
http://www.mangareader.net/boku-no-hero-academia/1
http://www.mangareader.net/boku-no-hero-academia/2

**Comment by Xonshiz** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [To Fix/Maintain](https://trello.com/c/ax62PL1F/6-to-fix-maintain)

**Comment by Xonshiz** [comment]
Just replicated this issue on my end. Will try to fix this by today itself. Keep an eye out for the update!

**Comment by Xonshiz** [comment]
This has been fixed and Python source code has been updated. Will release the windows binary with the fixed bugs in a while.
