### ISSUE TITLE
Range argument not working

### ISSUE THREAD

**Issue by rawdpiper** [Xonshiz/comic-dl#69]
Tried downloading a range of chapters from a manga but it started right from chapter 1

http://www.mangareader.net/boku-no-hero-academia

[Error_Log.log](https://github.com/Xonshiz/comic-dl/files/1595112/Error_Log.log)

**Comment by Xonshiz** [comment]
Fixed!

**Comment by Xonshiz** [comment]
I've updated the windows binary. Get it from here : https://github.com/Xonshiz/comic-dl/releases/latest

**Comment by rawdpiper** [comment]
Thanks. And I want to add that I appreciate your commitment to this script very much. As soon as there's an issue you attend to it ASAP and get it fixed. Keep up the good work. 👍
