### ISSUE TITLE
--keep switch not working

### ISSUE THREAD

**Issue by StrangeDOS** [Xonshiz/comic-dl#72]
Using the 'keep' switch to keep the downloaded files, but they are still deleted after converting to .cbz

[Error_Log.log](https://github.com/Xonshiz/comic-dl/files/1613504/Error_Log.log)

**Comment by Xonshiz** [comment]
Happening on pdf as well. Replicated the issue on my side and found the reason. Will try to fix within 4-5 days.

**Comment by Xonshiz** [comment]
This has been fixed and updated windows Binary has been released. Check on your end!
