### ISSUE TITLE
.cbz not created.

### ISSUE THREAD

**Issue by StrangeDOS** [Xonshiz/comic-dl#73]
Thanks for fixing the problem with --keep.  However, after trying the update, here's what I saw happen...

1. images were downloaded
2. a .zip file was created
3. same .zip file was deleted

The images were left behind but the .cbz file never got created.
[Error_Log.log](https://github.com/Xonshiz/comic-dl/files/1616424/Error_Log.log)

Oh...and if I don't use the --keep switch, the .cbz is also not getting created.

**Comment by StrangeDOS** [comment]
Oh, just noticed this, if the --keep switch is used, the .cbz actually is created.  But its in the folder with the images, instead of in the parent folder (named after the comic title).

But if the --keep switch isn't used, then nothing gets saved.  The images are downloaded, and the folder that stores them is deleted.  No .cbz is kept at all.

**Comment by Xonshiz** [comment]
Replicated the  issue on my side.

**Comment by Xonshiz** [comment]
I've fixed this in the python code itself and pushed the code. Will try to fix #74 and then release the windows binary.
