### ISSUE TITLE
-rn switch acting weird

### ISSUE THREAD

**Issue by StrangeDOS** [Xonshiz/comic-dl#74]
The range switch isn't working as expected.  In the example below, I'm trying to download 58-62.  What it actually does is download 89, then 88, 87, 86...and so on.
[Error_Log.log](https://github.com/Xonshiz/comic-dl/files/1616740/Error_Log.log)

C:\Program Files\nodejs>comic_dl -i http://readcomiconline.to/Comic/Creepy-1964 -dd f:\DownloadComic --convert cbz --quality high --keep yes -rn 58-62 -v

***Starting the script in Verbose Mode***

Downloading Full!
     =====================================================================
                            Manga Name : Creepy 1964
                          Chapter Number - Issue - 89
     =====================================================================

**Comment by Xonshiz** [comment]
This should be fixed by now. Grab the latest windows binary for the included fix.

**Comment by StrangeDOS** [comment]
Working great now!  Thanks!
