### ISSUE TITLE
Documentation bug

### ISSUE THREAD

**Issue by StrangeDOS** [Xonshiz/comic-dl#76]
Looks like you added a couple of new switches ( --config-make and --auto-download).  

The "List of Arguments" section of your page doesn't explain how they work.

Just trying to help out :)

**Comment by Xonshiz** [comment]
Whoops! Forgot to add them there. But, you can take a look at their usage [here](https://github.com/Xonshiz/comic-dl#making-the-configuration-file)

**Comment by StrangeDOS** [comment]
Sweet.  Like the idea of the config file. 

Note:  I hit your patreon page today. :)

**Comment by Xonshiz** [comment]
Hey! Yes,  I  saw that. Thank you for that @StrangeDOS .Keeps the enthusiasm up :)

**Comment by Xonshiz** [comment]
Reverted this feature. Hence, closing this issue.
