### ISSUE TITLE
Config file and -keep

### ISSUE THREAD

**Issue by StrangeDOS** [Xonshiz/comic-dl#78]
It doesn't appear that the config file allows you to enter an option to 'keep', like using the --keep switch.

For me, this would be nice.  I like to keep all the pages until I have the full, completed set downloaded.  

So I guess this is more of a feature request. :)

**Comment by Xonshiz** [comment]
Try passing "--keep True" along in the arguments and get back to me please. It should work.

**Comment by Xonshiz** [comment]
With this release, I've made the "--keep" to True. Which means that by default, it won't delete anything. For now I'm not adding any more commands into that config file. This is like a test stage for it. First I need to ensure that everything is working just fine. After that, I plan to include all the arguments into the Config file :)

**Comment by StrangeDOS** [comment]
Okay.  I'll try again later.  thanks!

**Comment by Xonshiz** [comment]
Reverted this feature. Hence, closing this issue.
