### ISSUE TITLE
[13068] Failed to execute script __main__

### ISSUE THREAD

**Issue by StrangeDOS** [Xonshiz/comic-dl#79]
I've seen this happen from time to type but I actually caught it today.  Every now and then I'll try to download and I see this output....

***Starting the script in Verbose Mode***

Downloading Full!
Traceback (most recent call last):
  File "comic_dl\__main__.py", line 10, in <module>
  File "comic_dl\comic_dl.py", line 178, in __init__
  File "comic_dl\honcho.py", line 98, in checker
  File "comic_dl\sites\readcomicOnlineto.py", line 30, in __init__
  File "comic_dl\sites\readcomicOnlineto.py", line 135, in full_series
  File "comic_dl\sites\readcomicOnlineto.py", line 40, in single_chapter
IndexError: list index out of range
[13068] Failed to execute script __main__

However, if I manually copy the URL for each issue/book, then I can download them without issue.

Attaching log.
[Error_Log.log.txt](https://github.com/Xonshiz/comic-dl/files/1627773/Error_Log.log.txt)

**Comment by StrangeDOS** [comment]
I located 3 other titles that have the same behavior.

http://readcomiconline.to/Comic/E-man-1993
http://readcomiconline.to/Comic/E-Man-The-Idol
http://readcomiconline.to/Comic/Final-Crisis-Sketchbook 

I didn't capture logs for them.  Let me know if you want me to.

**Comment by rawdpiper** [comment]
@StrangeDOS  do you still get this issue? Just ran the script with RCO website for the first time and I'm getting this exact same issue so i don't think its the issue of IP ban.
These are the links i got the problem with:
[http://readcomiconline.to/Comic/The-X-Men-vs-the-Avengers](url)
[http://readcomiconline.to/Comic/Marvel-Universe-Avengers-Earth-s-Mightiest-Heroes](url)

**Comment by Xonshiz** [comment]
Replicated the issue on my end, will look into it when I get some time.
http://readcomiconline.to/Comic/E-man-1993

**Comment by StrangeDOS** [comment]
See bug #89 

The current bug, #79, has been resolved.  However, bug #89 seems to be related to this bug.
