### ISSUE TITLE
Unable to run script

### ISSUE THREAD

**Issue by Maximilian-N** [Xonshiz/comic-dl#8]
I am sorry I have no verbose output, but the script refuses to run at all. I followed the installation guide with no errors, but at the final step it does not work:

`maximilian@PerfectServer:~/scripts/comic-dl-master/comic_dl$ ./comic_dl.py --verbose
Traceback (most recent call last):
  File "./comic_dl.py", line 10, in <module>
    from honcho import url_checker
  File "/home/maximilian/scripts/comic-dl-master/comic_dl/honcho.py", line 12, in <module>
    from future import standard_library
ImportError: No module named future`

Python version is 2.7.12
PhantomJS version is 2.1.1
Linux version is 16.04.4 server

The script has execute permissions and all the files seem to have downloaded correctly.

**Comment by Xonshiz** [comment]
Could you please try running these one by one (in order)
```
comic_dl.py --version
comic_dl.py --help
comic_dl.py --verbose -i "http://kissmanga.com/Manga/Shingeki-no-Kyojin"
```

And please [read how to post issues](https://github.com/Xonshiz/comic-dl#reporting-issues) and reformat your query in this issue only.

**Comment by Xonshiz** [comment]
Wait, actually looking at your query output... try running this : 

```
python pip install future
```

**Comment by Maximilian-N** [comment]
Ups. Just running a 

`pip install -r requirements.txt`

did the job. It now seems to work. 
As this is only listed in the "Windows" part of the guide I skipped over it.  Thank you.

**Comment by Xonshiz** [comment]
Whoops, I'll fix that one. :)
