### ISSUE TITLE
How to know when done?

### ISSUE THREAD

**Issue by StrangeDOS** [Xonshiz/comic-dl#81]
Feature Request:
It would be great to have a way of knowing when the series is complete without having to go back to the website.

Example:  Even with the config file and auto-download, you don't know when you have the last comic when the series is complete.  You could simply drop in a 1kb file that says, "Series Complete".  Then you know to stop checking that title or remove it from your config file.

![image](https://user-images.githubusercontent.com/20542548/34911517-35a38020-f89a-11e7-8e54-a2bf458dcb07.png)

**Comment by Xonshiz** [comment]
Hey, in a practical situation, there's no way to know whether a series has been done or not. Let's say that you've downloaded all the latest chapters that are available on a website. But, for some reason, the next chapter doesn't come out on a regular time. It comes out after 2-3  months, the script will believe that the series doesn't have any more chapters to come and it'll remove the link from the file.

The delay in release may not be common for Comic Books, but, it is very common in the Manga's cases. Releases may come after 1 month, 2 month or maybe even 6 months (yes, 6 months).

It's a nice feature to have, but there's no way for a script to know whether they're done with the chapters or not. Hence, it is not implementable, sorry.

**Comment by Xonshiz** [comment]
Oh I read that second part of your issue properly now. Adding more files to read from and write to, will increase the script's working time for no reason. Plus, I still need to fix that issue with the config file making this a ransomware.

**Comment by StrangeDOS** [comment]
Understood.  👍
