### ISSUE TITLE
Zip files being created for already downloaded comics

### ISSUE THREAD

**Issue by pnupy** [Xonshiz/comic-dl#82]
When I set the program to download a range of comics that includes already downloaded ones, it tries to redownload them, and when it does it creates a zip file (which I assume would be changed to cbz) and leaves it in the same folder as the cbz. It seems that when it tries to create the cbz file and fails due to it already existing, it doesn't delete the zip.

**Comment by Xonshiz** [comment]
Yes, that's a known issue. It won't be able to create a new file with the same name in the same directory. You need to remove either of these. This is something that each and every OS implements. I'd rather not delete the new un-movable file because there can be various reasons of failure.
