### ISSUE TITLE
503 Response when downloading from readcomiconline.to

### ISSUE THREAD

**Issue by santiagoperez** [Xonshiz/comic-dl#84]
I am using Mac. When I try to call the main script and download something, I get a 503 error. The same command (with the same parameters) was working 1 week ago (and I tried with the same version and after updating), so I do not know if the site just changed something.

Here the Error_log.log posted
./__main__.py -i "http://readcomiconline.to/Comic/Star-Wars-2015" --sorting asc --range 1-1 --convert cbz --keep False --verbose

DEBUG: Arguments Provided : Namespace(auto_download=False, chapter_id=None, config_make=False, convert=['cbz'], download_directory=None, force_download=False, input=['http://readcomiconline.to/Comic/Star-Wars-2015'], keep=['False'], manga_language='0', page_id=None, password=['None'], quality='True', range=['1-1'], search=None, skip_cache='0', sorting=['asc'], username=['None'], verbose=True, version=False)
DEBUG: Operating System : Darwin - 17.3.0 - Darwin Kernel Version 17.3.0: Thu Nov  9 18:09:22 PST 2017; root:xnu-4570.31.3~1/RELEASE_X86_64
DEBUG: Python Version : 2.7.10 (64bit)
DEBUG: Comic Url : http://readcomiconline.to/Comic/Star-Wars-2015
DEBUG: Selected Domain : readcomiconline.to
DEBUG: Starting new HTTP connection (1): readcomiconline.to
DEBUG: http://readcomiconline.to:80 "GET /Comic/Star-Wars-2015 HTTP/1.1" 503 None
Error_Log.log (END)

If I try to download a single issue:

./__main__.py -i "http://readcomiconline.to/Comic/Star-Wars-2015/Issue-41?id=128067" --convert cbz --keep False --verbose

Error_log.log
DEBUG: Arguments Provided : Namespace(auto_download=False, chapter_id=None, config_make=False, convert=['cbz'], download_directory=None, force_download=False, input=['http://readcomiconline.to/Comic/Star-Wars-2015/Issue-41?id=128067'], keep=['False'], manga_language='0', page_id=None, password=['None'], quality='True', range='All', search=None, skip_cache='0', sorting=None, username=['None'], verbose=True, version=False)
DEBUG: Operating System : Darwin - 17.3.0 - Darwin Kernel Version 17.3.0: Thu Nov  9 18:09:22 PST 2017; root:xnu-4570.31.3~1/RELEASE_X86_64
DEBUG: Python Version : 2.7.10 (64bit)
DEBUG: Comic Url : http://readcomiconline.to/Comic/Star-Wars-2015/Issue-41?id=128067
DEBUG: Selected Domain : readcomiconline.to
DEBUG: Starting new HTTP connection (1): readcomiconline.to
DEBUG: http://readcomiconline.to:80 "GET /Comic/Star-Wars-2015/Issue-41?id=128067&readType=1 HTTP/1.1" 503 None

**Comment by Xonshiz** [comment]
Please refer to #83 . RCO does this when you hit them up too many times. Please follow the procedure I and @StrangeDOS have written.
