### ISSUE TITLE
Folders getting deleted/Extra zip files created

### ISSUE THREAD

**Issue by StrangeDOS** [Xonshiz/comic-dl#86]
Okay.  I found an issue with the auto auto-download.  

Here is the sequence of events.

Downloaded “Black Panther Soul Of A Machine” using the following command…
comic_dl -i http://readcomiconline.to/Comic/Black-Panther-Soul-of-a-Machine/Issue-1?id=128756 -dd f:\DownloadComic --convert cbz --quality high --keep yes

This created the files/folders in attached file image1.jpg
That’s four folders with .jpgs inside, four .cbz files, and an extra folder and file (which has some metadata in it)

Then run comic_dl auto-download.  This resulted in the changes seen in attached file image2.jpg.

The folder for ‘Issue – 4’ was removed, and a second comic file for ‘Issue -4’ was created as a .zip file.

If I were to run comic_dl auto-download again, it would delete the folder for ‘Issue – 3’ and make a .zip file for issue 3....and so on.
![image1](https://user-images.githubusercontent.com/20542548/34930459-72ffe9c4-f997-11e7-9646-d28af5fbf88e.jpg)
![image2](https://user-images.githubusercontent.com/20542548/34930460-732059e8-f997-11e7-9461-c839015056e1.jpg)
[Error_Log.log](https://github.com/Xonshiz/comic-dl/files/1630654/Error_Log.log)
[comic_dl_config.config.txt](https://github.com/Xonshiz/comic-dl/files/1630655/comic_dl_config.config.txt)

**Comment by Xonshiz** [comment]
Uh, this is some issue I was afraid of. The reason for deletion of Issue 4 and then 3 is that when the script queried OS for the list of directories in that black panther folder, the OS did not return the order of files in an ascending or descending order, but in in arbitrary order. This led the script to believe that latest issue is .. let's say 3. So, it'll download again from issue 3 and start replacing those files.

Now, as soon as it is done downloading the files, it's time to convert to cbz. So, it converted it to .zip, only to find that there's already a file name issue3.cbz, hence, couldn't move it.

This sounds so confusing and it IS confusing. I need to implement some other way to find out which was the latest last downloaded chapter.

**Comment by StrangeDOS** [comment]
How does that 1kb file work?  I used a sector editor to dump out the unnamed $DATA stream and could see some metadata in it but there were also some other characters that I assume were formatting of some sort.  So its not a straight text file.

**Comment by Xonshiz** [comment]
which file?

**Comment by StrangeDOS** [comment]
This file....

![image1](https://user-images.githubusercontent.com/20542548/34956636-0ac75912-f9f8-11e7-997c-5f7a2a3f9085.jpg)

**Comment by Xonshiz** [comment]
Ummm.. you know what? FTS. I'll rollback this update and re-write this with the other approach I had.That way, the script won't have to depend on the OS to hand the directory list. I'm working on some other project so I can't devote my time to comic-dl for a while I'll try to whip it out in 2-3 days and then I'll slowly try to fix other issues.

**Comment by StrangeDOS** [comment]
Okay.  I'll keep using 2018.01.10 until you have something new to test.  Its pretty stable as long as I keep an exception in MalwareBytes. :)

**Comment by Xonshiz** [comment]
Reverted this feature. Hence, closing this issue.
