### ISSUE TITLE
Auto-dl function not updating the manga chapters

### ISSUE THREAD

**Issue by rawdpiper** [Xonshiz/comic-dl#87]
[Error_Log.log](https://github.com/Xonshiz/comic-dl/files/1631762/Error_Log.log)
There are 101 chapters of the manga shingeki no kyojin [http://www.mangareader.net/shingeki-no-kyojin](url), I've already downloaded the chapters complete up to the latest chapter but I then intentionally moved the latest chapter (both the cbz format and the folder where the jpg pictures are stored) which is chapter 101 to another folder to test the `auto-dl` function. After running the `--config-make` command and inputing the above URL and the directory which the manga chapters are located which is `C:\Users\HP\Desktop\Manga\Shingeki No Kyojin`, I then ran the `--auto-dl` command, it runs then shows the total time taken and when i go back to check the folder nothing has been updated

**Comment by Xonshiz** [comment]
Reverted this feature. Hence, closing this issue.
