### ISSUE TITLE
Last comic on list is skipped

### ISSUE THREAD

**Issue by StrangeDOS** [Xonshiz/comic-dl#90]
Using new Windows binary (Script Version : 2018.01.19), on some of the titles, only some of the comics are downloading.

Example: 
http://readcomiconline.to/Comic/American-Vampire-Survival-of-the-Fittest

This title has FIVE comicbooks in it.
![image](https://user-images.githubusercontent.com/20542548/35157503-2b9c0414-fd02-11e7-92d2-50b8d7bee675.png)

However, only the first FOUR comicbooks are downloading.
![image](https://user-images.githubusercontent.com/20542548/35157559-59b5e6c6-fd02-11e7-9bfa-c12b07c2d576.png)

From the log....
DEBUG: All Links : ['American-Vampire-Survival-of-the-Fittest/Issue-1?id=55295', 'American-Vampire-Survival-of-the-Fittest/Issue-2?id=55296', 'American-Vampire-Survival-of-the-Fittest/Issue-3?id=55297', 'American-Vampire-Survival-of-the-Fittest/Issue-4?id=55298']

The fifth comicbook isn't being added to the 'All Links'.  

This isn't happening on all downloads.  Only two titles that I've noticed so far.

http://readcomiconline.to/Comic/American-Vampire-Survival-of-the-Fittest
http://readcomiconline.to/Comic/AmeriKarate
[Error_Log.log](https://github.com/Xonshiz/comic-dl/files/1647007/Error_Log.log)

**Comment by Xonshiz** [comment]
I think I know why. LOL. Wait, I'll push fix this issue on my end and will release the new binary tomorrow morning.
