### ISSUE TITLE
Missing placeholder

### ISSUE THREAD

**Issue by StrangeDOS** [Xonshiz/comic-dl#92]
The good news is that everything else seems to be working so far.  I've tested with a bunch of titles that were having trouble with comic_dl and everything is downloading.

However, we lost something that we had.  On titles that are not complete (shown on RCO as 'Ongoing'), comic_dl would drop a 1 KB placeholder file and an empty directory in the parent folder.

![image](https://user-images.githubusercontent.com/20542548/35206223-229cce6c-ff09-11e7-8bf4-a0c8113f0cb2.png)

This made sorting SOOOOO easy.  Any directory that had that 1 KB file and extra directory, I knew I needed to check periodically for updates.  Otherwise, I knew the collection was complete.

This was a SUPER useful feature.  But this last update dropped it.  Is there anyway we can get that added back into comic_dl?

**Comment by Xonshiz** [comment]
No. That's useless and a bug actually. It's not a feature, it never was..
😂 😂 😂 😂 😂.

**Comment by StrangeDOS** [comment]
Okay...it was a mighty useful bug.
