### ISSUE TITLE
Download directory

### ISSUE THREAD

**Issue by ducle2502** [Xonshiz/comic-dl#93]
I am using the 2018.01.22 windows binary release and I notice that the downloader creates a folder named "D" and saves all the comics there instead of the folder it is in. In previous releases it would just put the comics where it is. Is this an intended feature?

**Comment by Xonshiz** [comment]
Hey, please write a proper report, as mentioned in the read me, along with the verbose output log.

**Comment by StrangeDOS** [comment]
ducle2502, 
There is a switch you can use to control where your files are downloaded to (--dd).  This allows you to put your files where ever you like.  

Example:
comic_dl -i http://readcomiconline.to/Comic/DreamWorks-Dragons-Riders-of-Berk -dd f:\DownloadComic

In the example above, I'm downloading to the 'DownloadComic' folder on my F: drive.

If you aren't experiencing that, be sure to run a test using the --verbose switch and post the Error_Log so Xonshiz can see what happened.

**Comment by Xonshiz** [comment]
I'm just confused about this particular line : 

>I notice that the downloader creates a folder named "D" and saves all the comics there instead of the folder it is in. 

I need a verbose log for this part. This is a weird behavior. Because when I tested the script on my end, it worked just fine.

**Comment by Xonshiz** [comment]
Could you please upload the log again? I cannot see any attachment.

**Comment by ducle2502** [comment]
Here is the log.
[Error_Log.log](https://github.com/Xonshiz/comic-dl/files/1658599/Error_Log.log)

**Comment by StrangeDOS** [comment]
ducle2502, in the short term, you can use the --dd switch to put your files in the directory that you want.
Example:

comic_dl.exe -i http://readcomiconline.to/Comic/Books-of-Magick-Life-During-Wartime --convert cbz --keep no --dd d:\Ebooks

Xonshiz, sorry I missed this bug.  I always use the --dd switch, so I wouldn't have noticed it.  Could this be something like a weird PATH statement?  Maybe we should get ducle to post his PATH environment variable.  I notice that I've got nodejs in my PATH. 
![image](https://user-images.githubusercontent.com/20542548/35319129-794dfe30-00ac-11e8-94c9-9c31b92cc4dc.png)

If he's got something like D:\Ebooks\D, that might explain it.

**Comment by Xonshiz** [comment]
I looked at the Error log and I tried the script on my end as well. Everything is working just fine. This is a weird issue. @ducle2502 , could you please post your system path variable settings, like @StrangeDOS did above?
