### ISSUE TITLE
Windows binary barfs on Noël

### ISSUE THREAD

**Issue by StrangeDOS** [Xonshiz/comic-dl#95]
Comic_dl seems to be having a problem with special characters. In this case, "ë".  No error log attached for this one as the process didn't get far enough to generate one.

C:\Program Files\nodejs>comic_dl -i http://readcomiconline.to/Comic/Batman-Noël -dd f:\DownloadComic --convert cbz  --quality high --keep yes --keep yes --verbose

***Starting the script in Verbose Mode***

Traceback (most recent call last):
  File "comic_dl\__main__.py", line 10, in <module>
  File "comic_dl\comic_dl.py", line 219, in __init__
  File "comic_dl\honcho.py", line 98, in checker
  File "comic_dl\sites\readcomicOnlineto.py", line 28, in __init__
  File "comic_dl\sites\readcomicOnlineto.py", line 93, in full_series
  File "comic_dl\globalFunctions.py", line 29, in page_downloader
  File "requests\sessions.py", line 521, in get
  File "site-packages\cfscrape\__init__.py", line 39, in request
  File "requests\sessions.py", line 494, in request
  File "requests\sessions.py", line 437, in prepare_request
  File "requests\models.py", line 305, in prepare
  File "requests\models.py", line 355, in prepare_url
  File "encodings\utf_8.py", line 16, in decode
UnicodeDecodeError: 'utf8' codec can't decode byte 0xeb in position 41: unexpected end of data
[16764] Failed to execute script __main__

**Comment by StrangeDOS** [comment]
Actually it did make a log.  
[Error_Log.log](https://github.com/Xonshiz/comic-dl/files/1665554/Error_Log.log)

**Comment by Xonshiz** [comment]
Thanks for notifying. The same issue was on anime-dl where these non-utf-8 characters caused problems. I'll look into this.

**Comment by Xonshiz** [comment]
I've been at it for past 2-3 hours and I've reached following conclusion : 
1.) Python 2 uses "ASCII" as character encoding internally. So, anything that has weird characters that are not going to be converted to ASCII, it'll fail.

2.) Changing "system default encoding" in Python 2 isn't a good idea.

3.) Python 3 works internally with utf-8 by default

Now, if you really want to download from such URLs, you will need to change your system's terminal's character encoding to "utf-8" or "latin-1", which I do not recommend.
The script works just fine with python 3 in my IDE (Pycharm), but fails on PowerShell, because of what I mentioned above. There's nothing I can do about this issue. At least not now.

**Comment by Xonshiz** [comment]
There's a reason why I don't like working with encoding. It may work on my system because of my environment, but it may not work on yours. Need help with this one.

**Comment by StrangeDOS** [comment]
If I'm using the Windows binary, is Python even in play?

**Comment by Xonshiz** [comment]
No, it isn't. But, your terminal is. I did find a way to download those "special urls" though. You're gonna have to convert those special characters. For example : 

```
http://readcomiconline.to/Comic/Batman-Noël
```

would turn into :
```
http://readcomiconline.to/Comic/Batman-No%C3%ABl
```

You could simple copy the URL, paste it in Notepad and it should give you an encoded url, which should work. Try it on your end and let me know.

**Comment by StrangeDOS** [comment]
I get it.  This workaround is fine for me.  Feel free to close the bug.  This is easy enough to deal with on the client/user side.   :)

**Comment by StrangeDOS** [comment]
I did some testing.  As it turns out, your workaround doesn't work.

http://readcomiconline.to/Comic/Batman-No%C3%ABl

That url fails.  However, it did get me an idea.  I looked up the HEX code for ë, which is EB, and tried that instead.

http://readcomiconline.to/Comic/Batman-No%EBl

That works fine.  :)

**Comment by Xonshiz** [comment]
Weird, in my case the one I gave worked. See, this is why I hate these things lol.

**Comment by DavidKDean** [comment]
I know this is a Necro - But I was reading through the issues here and a thought hit me. Why not set the CHCP during the execution of the script?

Example:

[Console]::OutputEncoding = [Text.UTF8Encoding]::UTF8

Or to use chcp.com:
& "$env:windir\system32\chcp.com" 65001

You could also use a bat to set it as well - The end user will never notice this in the first place:

@Echo Off
CHCP 65001

This eliminates the end user having to change their code pages - And allows for your scripts to work out of the box.

Just a thought.

**Comment by Xonshiz** [comment]
Hey David,

This seems doable. I'll take a look at this and see what can be done from python itself and will try to implement it. Thank you for the detailed information :)

**Comment by DavidKDean** [comment]
From my understanding - Python3 is Unicode out of the box by Default, correct?

Are you still using Python2.7? If thats the case - Maybe this will help:

https://www.python.org/dev/peps/pep-0263/

**Comment by Danieltrue** [comment]
Pls when ever I open my comic_dl.exe it automatically close so what should I do.

**Comment by Xonshiz** [comment]
@DavidKDean I've already added "shebang" in every file (most, if not all). Python 2 is weird with encoding.. :(

**Comment by Xonshiz** [comment]
Can anyone confirm whether this is still an issue or not?

**Comment by darodi** [comment]
binaries are built using python 3.9 and most of the source users have migrated to python 3.x or docker
IMHO we could close this issue.

**Comment by Xonshiz** [comment]
I'm also inclined towards closing this one. Since no one has replied back in the last few weeks, I'll take it as "working as expected".
