### ISSUE TITLE
I can't execute the .exe (Binary) file!

### ISSUE THREAD

**Issue by DyeffersonAz** [Xonshiz/comic-dl#97]
It shows a cmd window with a simple line in it:

![image](https://user-images.githubusercontent.com/16638560/35482624-165c056c-041f-11e8-8415-930cac346341.png)

And it suddenly closes. Unfortunately, I have no more information about it, considering that I already have Node.js installed and in my %PATH%

**Comment by Xonshiz** [comment]
This is a command line utility that requires "arguments". Double clicking it won't work. Please check the "Usage" section of readme.
