### ISSUE TITLE
[Feature Request] To Show how many pages that issue have.

### ISSUE THREAD

**Issue by DyeffersonAz** [Xonshiz/comic-dl#98]
That is a suggestion:

![image](https://user-images.githubusercontent.com/16638560/35484493-adafe556-0437-11e8-84c5-82374012eb21.png)

It is to the person know how long does it will take

Information in all forms are good ;)

**Comment by Xonshiz** [comment]
Sure :)

**Comment by DyeffersonAz** [comment]
When will be the next update?

**Comment by Xonshiz** [comment]
That is something nobody can answer.
