### ISSUE TITLE
Bring back the Config file

### ISSUE THREAD

**Issue by StrangeDOS** [Xonshiz/comic-dl#99]
I know you had to yank it to resolve some other problems you were fixing, but could we get it back now?  PLEASE!!!

**Comment by Xonshiz** [comment]
It is already present. Thanks to @dsanchezseco .  Read it here : https://github.com/Xonshiz/comic-dl#auto-download

**Comment by dsanchezseco** [comment]
@Xonshiz open it as the config generator is missing. Assign it to me if you want, I'll try to develop it tonight/tomorrow ASAP. 

@StrandeDos you can create the config meanwhile manually, see the example (https://github.com/Xonshiz/comic-dl/blob/master/comic_dl/config.json.example).

**Comment by StrangeDOS** [comment]
Thanks.  I'll hold off until @dsanchezseco config generator is back.

**Comment by dsanchezseco** [comment]
Done! please test and gen windows binary 😄

**Comment by Xonshiz** [comment]
I'm closing this, as @dsanchezseco has fixed this issue. I'll release binary in a few hours. If you face any issues, please feel free to re-open this issue.
